---
title: "modelCompProbByMont_markdown"
author: "Victor Møller"
date: "30 mar 2019"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)
p_load(caTools, data.table, permute, matrixStats, MCMCpack)

```

paths

```{r}

baseDir <- "."
scriptDir <- paste0(baseDir, "/src/functions")
outputDir <- paste0(baseDir, "/data/modelComparison")

```

functions

```{r}
source(paste0(scriptDir, "/calculateDet.R"))
source(paste0(scriptDir, "/constants.R"))
source(paste0(scriptDir, "/convertBinary.R"))
source(paste0(scriptDir, "/modelToStr.R"))
source(paste0(scriptDir, "/strToModel.R"))
source(paste0(scriptDir, "/generateModels.R"))
source(paste0(scriptDir, "/compareModels.R"))
source(paste0(scriptDir, "/searchModel.R"))
source(paste0(scriptDir, "/generateY.R"))
source(paste0(scriptDir, "/generateXSet.R"))
source(paste0(scriptDir, "/getBetas.R"))
source(paste0(scriptDir, "/modelSimilarByInteraction.R"))
source(paste0(scriptDir, "/modelSimilarByTerm.R"))
source(paste0(scriptDir, "/getModelSelectionConstant.R"))
source(paste0(scriptDir, "/getModelComparison.R"))

```

input parameters

```{r}
## Number of factors
k = 3

## Sigma (Error variance)
sigmas = c(0.2, 0.5, 0.8) #we can add element to this list. NB. we'll have to change correspondingly in "noReplicator"

## Model Selection
mss = c("AIC", "Schwarz")

## Sample size
sampleSize = 100

## Number of independent samples on which model comparison statistic is based
nIter = 1e5

## Generate all models
models = generateModels(k)
models[[1]] = t(as.matrix(models[[1]]))
L = length(models)

## Correlation
correlation = 0.2

## Initialize
xset = generateXSet(sampleSize, k, correlation)

ggplot(xset, aes(X1)) +
  geom_density()

ggplot(xset, aes(X2)) +
  geom_density()

ggplot(xset, aes(X3)) +
  geom_density()

# Get Model Selection Constant for all Models
msConstant = getModelSelectionConstant(models, xset)

for( ms in 1:length(mss) ) {
  for( s in 1:length(sigmas) ) {
    for( i in 1:L ) {
      tModel = models[[i]] # True Model
      ProbMC = getModelComparison(xset, sampleSize, tModel, sigmas[s], models,
          nIter, mss[ms], msConstant)
      
      sigmaTxt = gsub("\\.", "", toString(sigmasTxt[s]))
      save(ProbMC, file = paste0(outputDir,
              '/ModelComparisonProbabilitiesSigma', sigmaTxt, mss[ms], i,
              '.RData', sep=""))
    }
  }
}

```

