---
title: "screeningplotsv2"
author: "Victor M?ller"
date: "11 sep 2019"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)
p_load(readr, tidyverse, ggplot2, RColorBrewer, reshape2, ggthemes, ggunchained)
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/tests")
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/tests/"
```


```{r}
test <- read.csv("new_selection.csv", sep = ",")
test <- test[,-1] #I saved terribly. 
```



```{r}
naming <- colnames(test)

testmelt <- test %>%
  melt(id = c(naming[1:5])) %>% #melting with proportions becoming variable and their values becoming values
  mutate(true_model = as.factor(true_model)) %>%
  mutate(true = ifelse(variable == "proportion_true", "True", "False")) %>% #making a identifying column in order to color for the plot
  mutate(variable = relevel(variable, ref = "proportion_true")) %>% #releveling so that proportion true is considered first
  mutate(variable = fct_rev(variable))  #releveling so that proportion true is considered last - this is done in order to make it the top layer in the overlay between different smooths. 


#what you want to plot
sigma_p <- 0.2
population_p <- "Tess"
network_p <- "Small"


```

```{r}
### we have goet to consider "studies" for the new stuff (cut-off) ###

g <- testmelt %>%
  filter(sigma == sigma_p, population == population_p, true_model == true_model_p, studies < 2000) %>%
  ggplot(aes(studies, value, color = true))+
  geom_point(alpha = 0.01) +
  geom_smooth(method = "loess", se = F, alpha = 0.1, size = 1.2, aes(labels = variable)) +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dotted", size = 1) + 
  labs(x = "Studies", y = "Proportion", color = "Proportion of different models", 
       title = "Proportion of agents at the true model",
       subtitle = paste("Network:", network_p, "|", "Population:", population_p, "|", "Sigma:", sigma_p, "|", "True Model:", true_model_p)) +
  theme_janco_point()

g
```

