---
title: "qualitative"
author: "Mikkel Werling & Victor M?ller"
date: "5/16/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

packages

```{r}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse)

```

paths

```{r}
baseDir <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1" #the "." stopped working. 
scriptDir <- paste0(baseDir, "/src/functions")
inputDir <- paste0(baseDir, "/data")
outputDir <- paste0(baseDir, "/data")
```

functions

```{r}
source(paste0(scriptDir, "/analysis.R"))
source(paste0(scriptDir, "/calculateDet.R"))
source(paste0(scriptDir, "/calculateDistance.R"))
source(paste0(scriptDir, "/compareModels.R"))
source(paste0(scriptDir, "/constants_3.R")) #new constants baby
source(paste0(scriptDir, "/convertBinary.R"))
source(paste0(scriptDir, "/generateBetas.R"))
source(paste0(scriptDir, "/generateModels.R"))
source(paste0(scriptDir, "/generateXSet.R"))
source(paste0(scriptDir, "/generateY.R"))
source(paste0(scriptDir, "/getBetas.R"))
source(paste0(scriptDir, "/getPredictors.R"))
source(paste0(scriptDir, "/modelSimilarByInteraction.R"))
source(paste0(scriptDir, "/modelSimilarByTerm.R"))
source(paste0(scriptDir, "/modelToStr.R"))
source(paste0(scriptDir, "/searchModel.R"))
source(paste0(scriptDir, "/seedGenerator.R"))
source(paste0(scriptDir, "/simulator.R"))
source(paste0(scriptDir, "/strToModel.R"))
#source(paste0(scriptDir, "/ABM.R")) #the ABM
#source(paste0(scriptDir, "/ABM1.R")) #new
#source(paste0(scriptDir, "/ABM2.R")) #new!!
source(paste0(scriptDir, "/ABM3.R")) #new!!
```

some_models, g & agentTurn

```{r}

#some models -  
load(paste0(baseDir, "/connectivity/loads/some_models"))

```


input parameters

```{r}

## Number of replications
replications <- 2 #100 originally, now 2. 

## Length of the simulation
turns <- 11000

## Number of factors
k <- 3

## Sigma (Error variance)
sigma <- 0.2

## Sample size
sampleSize <- 100

## generating 
load(paste0(baseDir, "/connectivity/loads/models")) #changed

## Identify the number of predictors of each model
predictors <- getPredictors(models)

## Generate Betas
weights <- generateBetas(models)

## True model
trueModel <- some_models[7] 
tModel <- strToModel(trueModel, k)

## Correlation
correlation <- 0.2

## modelCompare & selection
modelCompare <- BIC
modelSelection <- "hard"

## ndec
ndec = 4

## outputs
outputFile <- ".csv" #
paramFile <- ".rds"

## verbose
verbose <- TRUE
```

for output.

```{r}

criterion <- "BIC" #BIC
net_type <- "Lattice" #Lattice, Small-world
pop_type <- "All" #Bo, Tess, Mave, All
net_size <- 100 #100
tm <- 7 #for output

```

seed.

```{r}
## seeds
seeds <- seedGenerator(replications, paste0(inputDir, "/seeds.csv"))
```

running the ABM. 

```{r}

ABM3(replications, turns, models, k, 
    weights, sampleSize, correlation, sigma,
    modelCompare, modelSelection, inputDir, outputDir, outputFile, paramFile,
    verbose, ndec, seeds, some_models)

```

