---
title: "RR_TAT_RidgesRaincloud_MetascienceBA"
author: "Victor Møller"
date: "December 15, 2019"
output: html_document
---

updated 15-12-2019.
plots that we use only. 

```{r}
library(pacman)
p_load(readr, tidyverse, ggplot2, RColorBrewer, reshape2, ggthemes,
       viridis, ggridges, ggunchained, rlang, cowplot)
```


```{r}
setwd("~/CRUST-1/Paper2/data/outcomeMeasures")
RR <- read_csv("RR_TAT_Paper2.csv")

#prep TF. 
RR <- RR %>%
  mutate(network = factor(network),
        population = factor(population),
        sigma = factor(sigma),
        colab_cond = factor(colab_cond),
        net_size = factor(net_size),
        true_model = factor(true_model),
        colab_cond = recode(colab_cond,
                               NOLAB = "No",
                               COLAB = "Yes"))
```

raincloud prep

```{r}

#preparing raincloud (can be customized)
raincloud_theme = theme(
text = element_text(size = 10),
axis.title.x = element_text(size = 16),
axis.title.y = element_text(size = 16),
axis.text = element_text(size = 14),
axis.text.x = element_text(vjust = 0.5),
legend.title=element_text(size=16),
legend.text=element_text(size=16),
legend.position = "right",
plot.title = element_text(lineheight=.8, face="bold", size = 16),
panel.border = element_blank(),
panel.grid.minor = element_blank(),
panel.grid.major = element_blank(),
axis.line.x = element_line(colour = 'black', size=0.5, linetype='solid'),
axis.line.y = element_line(colour = 'black', size=0.5, linetype='solid'))

```

new directory & loading flatViolin

```{r}

setwd("~/CRUST-1")
baseDir <- "."
scriptDir <- paste0(baseDir, "/FunctionsLoads/Functions")
source(paste0(scriptDir, "/flatViolin.R"))

```

Prep

```{r}
melt_RR_TAT <- melt(RR, 
                    id.vars = c("replica", "network",
                                "population", "sigma", "true_model", 
                                "colab_cond"), 
                    measure.vars = c("RR", "TAT"), 
                    variable.name = "variable", 
                    value.name = "proportion")
```

Ridges plot: 

```{r}

RR_FUN2 <- function(.df, .var1, .sigma, .net1, .net2, .colab){
  
  var1 <- enquo(.var1)
  sigma <- enquo(.sigma)
  net1 <- enquo(.net1)
  net2 <- enquo(.net2)
  colab <- enquo(.colab)

  g <- .df %>%
      filter(sigma == UQ(sigma),
         colab_cond == UQ(colab),
         network == UQ(net1) | network == UQ(net2)) %>%
      ggplot(aes(x = proportion,
                 y = UQ(var1), 
                 color = variable,
                 fill = variable)) +
      geom_density_ridges(jittered_points = TRUE, scale = 0.8, 
                          rel_min_height = .01,
                          point_shape = "|", point_size = 1, size = 0.1, 
                          position = position_points_jitter(height = 0)) +
      scale_y_discrete(expand = c(0.01, 0)) +
      scale_x_continuous(expand = c(0,0), 
                         name = "Replication Rate (RR) & Time at the True Model (TAT)") +
      scale_fill_manual(values = c("#D55E0050", "#0072B250"), 
                        labels = c("Replication rate (RR)", 
                                   "Time at true model (TAT)")) +
      scale_color_manual(values = c("#D55E00", "#0072B2"), guide = "none") +
      scale_discrete_manual("point_color", values = c("#D55E00", "#0072B2"), 
                            guide = "none") +
      guides(fill = guide_legend("",
        override.aes = list(
        fill = c("#D55E00A0", "#0072B2A0"),
        color = NA, point_color = NA))
      ) +
      theme_ridges(center = TRUE) + 
      theme_janco_point() +
      theme(axis.text=element_text(size=15),
            axis.title=element_text(size=17),
            legend.title = element_text(size = 15),
        legend.text = element_text(size = 15)) 
  
g + labs(x = "RR & TAT",
         y = "True models", 
         fill = "Measure")
}

fig7_C <- RR_FUN2(melt_RR_TAT, true_model, 0.5, "Small", "Lattice", "Yes")
fig7_C
```

The correlation plot is loaded from the RR_scatterplot_MetascienceBA.Rmd doc

```{r}
Fig7_C <- fig7_C
Fig7_B <- Fig7_B #from TAT_T_MetascienceBA
Fig7_A <- Fig7_A #from RR_scatterplot_MetascienceBA

#combining the two figures: 
figure7_toprow <- plot_grid(Fig7_A, Fig7_C, labels = "AUTO", label_size = 30)



figure7 <- plot_grid(figure7_toprow, Fig7_B, 
                   labels = c("","C"), 
                   label_size = 30,
                   nrow = 2)

figure7


```



