---
title: "citation visualization"
author: "Mikkel Werling"
date: "12/6/2019"
output: html_document
---
_________
This document visualizes idealized networks as well as the networks used in the ABMs. 
_________



Loading packages

```{r}
library(pacman)
p_load(igraph, ggraph, networkD3, visNetwork, cowplot)
```

Generating the networks

```{r}

setwd("~/CRUST-1/Paper2/citationNetworks")

TOM <- readRDS("TOM.rds")

PT <- readRDS("PT.rds")

net_size <- 484

lattice <- make_lattice(length = 20, dim = 1, 
                        nei = 2, circular = T, directed = F)

small <- sample_smallworld(1, 20, 2, 0.05)
```

Plotting using ggraph

```{r}
tom_graph <- ggraph(TOM, "circle")+
  geom_node_point(aes(size = degree(TOM), alpha = degree(TOM)))+
  geom_edge_diagonal(alpha = 0.05)+
  labs(title = "Theory of Mind",
       size = "Degree",
       alpha = "Degree") + 
  theme_graph()

pt_graph <- ggraph(PT, "circle")+
  geom_node_point(aes(size = degree(PT), alpha = degree(PT)))+
  geom_edge_diagonal(alpha = 0.05)+
  labs(title = "Prospect Theory",
       size = "Degree",
       alpha = "Degree") + 
  theme_graph()

lattice_graph <- ggraph(lattice, "circle")+
  geom_node_point(aes(alpha = degree(lattice), size = 4))+
  geom_edge_link(alpha = 0.4)+
  labs(title = "Lattice",
       size = "Degree",
       alpha = "Degree") + 
  theme_graph()

small_graph <- ggraph(small, "circle")+
  geom_node_point(aes(alpha = degree(small), size = 4))+
  geom_edge_link(alpha = 0.4)+
  labs(title = "Small-world",
       alpha = "Degree") + 
  guides(size = F) + 
  theme_graph()


small_lattice <- plot_grid(lattice_graph, small_graph, nrow = 1)

citation_networks <- plot_grid(pt_graph, tom_graph, nrow = 1)

```
