---
title: "citation_network"
author: "Mikkel Werling"
date: "9/5/2019"
output: html_document
---
```{r}
library(pacman)
p_load(bibliometrix)
p_load(igraph)
p_load(ggraph)
p_load(tidyverse)
p_load(stringr)
```

Reading the data file

```{r}
D <- readFiles("http://www.bibliometrix.org/datasets/savedrecs.bib")

M <- convert2df(D, dbsource = "isi", format = "bibtex")

```

bibliometrix own analysis (don't run)

```{r}

results <- biblioAnalysis(M, sep = ";")

NetMatrix <- biblioNetwork(M, analysis = "collaboration", network = "authors", sep = ";")

# Plot the network
net=networkPlot(NetMatrix, n = 30, Title = "Collaboration Network", type = "fruchterman", size=T, remove.multiple=FALSE, labelsize=0.7,edgesize = 5)

A <- cocMatrix(M, Field = "AU", sep = ". ")

net <- biblioNetwork(A, analysis = "co-citation", network = "references", sep = ";")
```


parsing CR
```{r}
head(M$CR)
authors <- str_split(M$CR, ";") #authors are split by semicolon in the dataset

come_on <- lapply(authors, str_extract, "[^,]+") #extract all the first authors

data <- data.frame()

for (i in 1:291){ #hardcoded for the number of in the list of "come_on"
  assign("new_mode", as.data.frame(come_on[[i]]))
  new_mode$original <- M$AU[i]
  data <- rbind(new_mode,data)
}

data$original <- lapply(data$original, str_extract, "[^;]+")

el <- data %>%
  select(original, `come_on[[i]]`)

graphing <- graph_from_data_frame(el, directed = T)

E(graphing)$name <- as.character(data$original)

ggraph(graphing)+
  geom_node_point(aes(size = degree(graphing), alpha = degree(graphing)))+
  geom_edge_fan(alpha = 0.2)+
  theme_graph()

degree(graphing)

E(graphing)

```

Parsing the authors and the references

```{r}
cleaned_data <- el
cleaned_data <- na.omit(cleaned_data) #get rid of na
cleaned_data$`come_on[[i]]` <- as.character(cleaned_data$`come_on[[i]]`) #as character instead of factor
cleaned_data$number_detection <- str_detect(cleaned_data$`come_on[[i]]`, "[:digit:]") #get rid of digits
cleaned_data$punct_detection <- str_detect(cleaned_data$`come_on[[i]]`, "[:punct:]") #a bit redundant - there are a lot of dots in the names
cleaned_data$star_detection <- str_detect(cleaned_data$`come_on[[i]]`, "\\*") #stars in the names seemed to be a nuisance
cleaned_data$anon_detection <- str_detect(cleaned_data$`come_on[[i]]`, "ANONYMOUS") #don't want any anonymous in the data
cleaned_data$na_detection <- cleaned_data$`come_on[[i]]`=="NA" #if some were listed as na

data_new <- cleaned_data %>%
  filter(star_detection == F, number_detection == F, anon_detection == F)

#In order to make direct comparisons between authors and references, we have to make them exactly the same

data_new$`come_on[[i]]` <- str_replace_all(data_new$`come_on[[i]]`, "[:punct:]", "") #removing all the punctuation and replacing it with blank space

data_new$`come_on[[i]]` <- str_replace_all(data_new$`come_on[[i]]`, "[:space:]", "") #removing blank space from references
data_new$original <- str_replace_all(data_new$original, "[:space:]", "") #removing blank space from authors

data_new <- data_new %>%
  select(original, `come_on[[i]]`)

data_new$match <- data_new$original == data_new$`come_on[[i]]` #noting when authors quote themselves

data_new <- data_new %>%
  filter(match == F)

##check if the author is also ref 

data_new$ref <- data_new$`come_on[[i]]` %in% data_new$original

data_new <- data_new %>%
  filter(ref == T)

data_new_1 <- distinct(data_new) #removing duplicates 
data_new_1 <- data_new_1 %>%
  select(original, `come_on[[i]]`)

graphonology <- graph_from_data_frame(data_new_1, directed = F)

graphonology <- igraph::simplify(graphonology) #remove multiple edges and loops

ggraph(graphonology)+
  geom_node_point(aes(size = degree(graphonology), alpha = degree(graphonology)))+
  geom_edge_fan(alpha = 0.2)+
  theme_graph()

V(graphonology) #a lot less!

max(degree(graphonology)) 

main <- induced_subgraph(
  graphonology, V(graphonology)[components(graphonology)$membership == which.max(components(graphonology)$csize)]
) #includes only the main branch of the network

ggraph(main, "circle")+
  geom_node_point(aes(size = degree(main), alpha = degree(main)))+
  geom_edge_fan(alpha = 0.2)+
  theme_graph()

#save the file
saveRDS(main, "main.rds")

```

diagnostics

```{r}
average.path.length(main) #getting the average path length 

transitivity(main) #clustering coefficient 
closeness(main) #unsure what this really means - what kind of closeness measure is this?

assortativity_degree(g, directed = F)


#distribution of the degrees
deg.dist <- degree_distribution(main, cumulative=T, mode="all")
plot( x=0:max(degree(main)), y=1-deg.dist, pch=19, cex=1.2, col="orange", 
      xlab="Degree", ylab="Cumulative Frequency")
```

