---
title: "Plotting networks from the parameters"
author: "Mikkel Werling"
date: "5/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

reading all the parameter-files:

```{r}
setwd("~/CRUST-1/data/ABMdata/ABMrds/Sample_size_100/ABMrds2")

#readRDS

temp = list.files(pattern="*.rds")

#all in one
lattice_7 = lapply(temp[1:12], readRDS)

small_7 = lapply(temp[13:24], readRDS)
```

getting the adjacency matrix for all the runs in a param:

```{r}

small_matrix <- graph_from_adjacency_matrix(small_7[[2]][[3]][[9]], diag = F, mode = "undirected")

#for all conditions in a network and for all replicas
for (each in 1:12){
  for(runs in 1:50){
name <- paste("L", each, runs, sep = "_")
assign(name, graph_from_adjacency_matrix(lattice_7[[each]][[runs]][[9]], diag = F, mode = "undirected"))
  }
}
```

plotting the different networks:

```{r}
#plotting requires the type - insert the matrix name at both places
V(lattice_matrix)$type <- gsub("\\..*","",V(lattice_matrix)$name)

p1 <- ggraph(lattice_matrix, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link() + 
  geom_node_point(aes(colour = type, size = degree(lattice_matrix))) + #size according to degree
  geom_node_text(label = degree(lattice_matrix))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Small_world")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) +#plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

```
small world - same story
```{r}
#temp
for (each in 1:12){
  for(runs in 1:50){
name <- paste("SW", each, runs, sep = "_")
assign(name, graph_from_adjacency_matrix(small_7[[each]][[runs]][[9]], diag = F, mode = "undirected"))
  }
}

V(small_matrix)$type <- gsub("\\..*","",V(small_matrix)$name)

p3 <- ggraph(small_matrix, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link() + 
  geom_node_point(aes(colour = type, size = degree(small_matrix))) + #size according to degree
  #geom_node_text(label = degree(small_matrix))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Small-world")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) + #plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

p3
```
