---
title: "qwe"
author: "Victor Møller"
date: "11 sep 2019"
output: html_document
---

```{r}
#### PREPARATION #####
g <- sample_smallworld(1, 100, 2, 0.05)
V(g)$type <- rep(c("Bo", "Mave", "Tess"), c(98,1,1))


# Sampling agents 
V(g)$type <- sample(V(g)$type)
V(g)$name <- make.unique(V(g)$type) 
V(g)$model <- sample(some_models)
V(g)$model <- sample(V(g)$model)
matrix_g <- as_adjacency_matrix(g, sparse = F) 
agentTurn <- sample(V(g)$name, size = 11000, replace = T) 

## Select the token of agent
agentToken <- agentTurn[1] 
agentIndex <- which((V(g)$name) == agentToken)
gModel <- strToModel(V(g)$model[agentIndex], k)


```

```{r setup, include=FALSE}

### HELE KODEN ### 

#first we find the edges. 
edges_total <- names(which(matrix_g[, agentIndex] == 1)) #all edges from agent on turn.
edges_legible <- list() #empty list. 
for(i in edges_total){ #looping over those edges. 
    
    #token for the i'th edge.  
    edgeToken <- i #should be edgeToken, not agentToken (as before)
    
    #index for the i'th edge
    edge_agentIndex <- which((V(g)$name) == edgeToken)
    
    #checking their model against agent on turn. 
    #if same then nothing happens. 
    if(identical(gModel, strToModel(V(g)$model[edge_agentIndex],k))){
    }
    else { #if not the same then that edge is added to the list. 
      edges_legible[i] <- edgeToken
    }
}


#determining reserach strategy. 
if(length(edges_legible) == 0){ #if no edges in the list then strat. must be research. 
  strategy <- 'research'
} else{ #if there are edges in the list, then research strat. is probabilistic. 
  strategy <- sample(c('research', 'neighbor'), size = 1, prob = c(.50, .50))
}

#what happens on RESEARCH (old code)
if(strategy == "research"){ 
  if(V(g)$type[agentIndex] == "Tess"){ 
    model <- modelSimilarByTerm(gModel, models, mode="random",
                                modelSelection=modelSelection)
    
    ## Mave
  } else if(V(g)$type[agentIndex] == "Mave"){
    model <- models[[as.integer(runif(1, min=1, max=length(models)+1))]]
    
    ## Bo 
  } else if(V(g)$type[agentIndex] == "Bo"){
    model <- modelSimilarByInteraction(gModel, models, mode="random",
                                       modelSelection=modelSelection)
  }
  
} else{ #what happens on NEIGHBOR (could be else if, but it has to be if not research)
  chosen_edge <- sample(edges_legible, size = 1) #sampling just 1 from the list. 
  edge_agentIndex <- which((V(g)$name) == chosen_edge) #finding index.
  model <- strToModel(V(g)$model[edge_agentIndex],k) #finding model. 
}



```

```{r}

#### superfluous now ####
if(strategy == "neighbor"){
  edges_total <- names(which(matrix_g[, agentIndex] == 1))
  edge_legible <- list() #empty list. 
  for(i in edges_total){
      
      #which one  
      edgeToken <- i #should be edgeToken, not agentToken. 
      
      #agents
      edge_agentIndex <- which((V(g)$name) == edgeToken)
      
      #gModel = model of agent on turn. Other side = model of edge. 
      if(identical(gModel, strToModel(V(g)$model[edge_agentIndex],k))){
      }
      else {
        edges_legible[i] <- edgeToken
      }
  }
  chosen_edge <- sample(edges_legible, size = 1) #sampling just 1. 
  edge_agentIndex <- which((V(g)$name) == chosen_edge)
  model <- strToModel(V(g)$model[edge_agentIndex],k)
}
```

