---
title: "screeningplotsv2"
author: "Victor M?ller"
date: "11 sep 2019"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)
p_load(readr, tidyverse, ggplot2, RColorBrewer, reshape2, ggthemes)
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/new_data")
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/new_data/"
```

loading data & binding together.

```{r}

#file-names
temp <- list.files(pattern="*csv")

#loading them 
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ";"))

#bind all latice together. 
all <- mget(ls(pattern="*csv")) %>%
              bind_rows()

#remove all the old shit 
rm(list=setdiff(ls(), "all")) #lattice_all_0.8 lacking turn 14. 

```

removing columns 

```{r}

#selecting the columns we want. 

mycols <- c("population", 
            "sigma",
            "true_model",
            "studies",
            "network",
            "proportion_1",
            "proportion_2",
            "proportion_3",
            "proportion_4",
            "proportion_5",
            "proportion_6",
            "proportion_7",
            "proportion_8",
            "proportion_9",
            "proportion_10",
            "proportion_11",
            "proportion_12",
            "proportion_13",
            "proportion_14",
            "proportion_true")

subset <- all %>%
  select(mycols)

naming <- colnames(subset)

```

```{r}


ggplot(subset, aes(studies, proportion_true)) +
  geom_point() +
  geom_smooth()
  
```


```{r}
df <- subset %>%
  melt(id = c(naming[1:5])) %>% #melting with proportions becoming variable and their values becoming values
  mutate(true_model = as.factor(true_model)) %>%
  mutate(true = ifelse(variable == "proportion_true", "True", "False")) %>% #making a identifying column in order to color for the plot
  mutate(variable = relevel(variable, ref = "proportion_true")) %>% #releveling so that proportion true is considered first
  mutate(variable = fct_rev(variable)) #releveling so that proportion true is considered last - this is done in order to make it the top layer in the overlay between different smooths.

#what you want to plot
sigma_p <- 0.2
population_p <- "Tess"
network_p <- "Small-world"
#true_model_p <- 7

```

```{r}

g <- df %>%
  filter(sigma == sigma_p, population == population_p, network == network_p) %>%
  ggplot(aes(studies, value, color = true))+
  geom_point(alpha = 0.01) +
  geom_smooth(method = "loess", se = F, alpha = 0.1, size = 1.2, aes(labels = variable)) +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dotted", size = 1) + 
  labs(x = "Studies", y = "Proportion", color = "Proportion of different models", 
       title = "Proportion of agents at the true model",
       subtitle = paste("Network:", network_p, "|", "Population:", population_p, "|", "Sigma:", sigma_p, "|", "True Model:", true_model_p)) +
  theme_janco_point()

g
```

