---
title: "Plot for replications of one run"
author: "Mikkel Werling"
date: "5/21/2019"
output: html_document
---


```{r}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, devtools, ggunchained)
```
read the data

```{r}
small_100_m7 <- read.csv("~/CRUST-1/data/model7csv/small_epi_0.5_BIC_100_hard_100.csv", sep = ",")
```

downsampling

```{r}
small_100_m7 <- small_100_m7[seq(1, nrow(small_100_m7), 25), ]
```

as.factor on replica for plotting 

```{r}
small_100_m7$replica <- as.factor(small_100_m7$replica)
```



Qualitative plot of Replications for one run
```{r}

small_100_m7 <- small_100_m7 %>%
  mutate(replica = as.factor(replica)) #making a identifying column in order to color for the plot

### SMOOTHING SOLUTION ###

q <- small_100_m7 %>%
  filter(sigma == 0.2, population == "Bo", network == "Small") %>%
  ggplot(aes(studies, proportion_true, color = replica))+
  geom_point(alpha = 0.01) +
  geom_smooth(alpha = 0.005) +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dashed", size = 1) + 
  labs(y = "Proportion", color = "Iterations", title = "Iterations of one run") + 
  theme_janco_point() + 
  theme(legend.position = "none")

q

### BOXPLOT SOLUTION ###
q <- small_100_m7 %>%
  filter(sigma == 0.2, population == "Bo", network == "Small") %>%
  ggplot(aes(replica, proportion_true, color = replica))+
  geom_point(alpha = 0.01) +
  geom_violin() +
  geom_boxplot(alpha = 0.4) + 
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dashed", size = 1) + 
  labs(y = "Proportion", color = "Iterations", title = "Iterations of one run") + 
  theme_janco_point() + 
  theme(legend.position = "none")

q
```