---
title: "networks"
author: "Mikkel Werling"
date: "5/29/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Plotting lattice and small world networks

```{r}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, devtools, ggunchained)

g <- make_lattice(length = 10, dim = 1, nei = 2, circular = T, directed = F)

V(g)$type <- sample(c("Bo", "Mave", "Tess"))

V(g)$name <- make.unique(V(g)$type)

p1 <- ggraph(g, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link() + 
  geom_node_point(aes(colour = type, size = 4)) + #size according to degree
  #geom_node_text(label = degree(g))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Lattice", subtitle = "10 agents | K = 2")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) +#plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

#p1

t <- sample_smallworld(1, 10, 2, 0.05)

V(t)$type <- sample(c("Bo", "Mave", "Tess"))

V(t)$name <- make.unique(V(t)$type)

p2 <- ggraph(t, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link(aes(colour = name == "Mave")) + 
  geom_node_point(aes(colour = type, size = 4)) + #size according to degree
  #geom_node_text(label = degree(g))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Small-world", subtitle = "10 agents | K = 2 | Rewiring probability = 0.05")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) +#plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

p2

#p2

g <- make_lattice(length = 100, dim = 1, nei = 2, circular = T, directed = F)

V(g)$type <- sample(c("Bo", "Mave", "Tess"))

V(g)$name <- make.unique(V(g)$type)

p3 <- ggraph(g, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link() + 
  geom_node_point(size = 2, aes(colour = type)) + #size according to degree
  #geom_node_text(label = degree(g))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Lattice", subtitle = "100 agents | K = 2")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) +#plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

#p3


t <- sample_smallworld(1, 100, 2, 0.05)

V(t)$type <- sample(c("Bo", "Mave", "Tess"))

V(t)$name <- make.unique(V(t)$type)

p4 <- ggraph(t, layout = "circle", circular= F) + #circular so it fits with the other plots
  geom_edge_link() + 
  geom_node_point(size = 2, aes(colour = type)) + #size according to degree
  #geom_node_text(label = degree(g))+ #having each node also have text with their degree
  labs(x = NULL, y = NULL, title = "Small-world", subtitle = "100 agents | K = 2 |  Rewiring probability = 0.05")+ #title and remove axis
  scale_colour_manual(values = wes_palette(n = 10, name = "Darjeeling1", type = "continuous")) + #colors
  guides(size = F) +#plotting the network using ggraph. Layout can be altered. Removes the legend for degree. 
  theme_graph()

#p4

all_plots <- plot_grid(p1, p2, p3, p4)

all_plots



```

