---
title: "Plot for replications of one run"
author: "Mikkel Werling"
date: "5/21/2019"
output: html_document
---


```{r}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse)
```


Qualitative plot of Replications for one run
```{r}
small_epi_0.5_BIC_100_hard_100.csv <- read.csv("~/CRUST-1/data/model7csv/small_epi_0.5_BIC_100_hard_100.csv", sep = ",")

small_epi_0.5_BIC_100_hard_100.csv <- small_epi_0.5_BIC_100_hard_100.csv[seq(1, nrow(small_epi_0.5_BIC_100_hard_100.csv), 25), ]

small_epi_0.5_BIC_100_hard_100.csv$replica <- as.factor(small_epi_0.5_BIC_100_hard_100.csv$replica)

epi_qual_plot <- ggplot(small_epi_0.5_BIC_100_hard_100.csv, aes(timestep, proportion_7, labels = replica))+
  geom_point(alpha = 0.01) +
  geom_smooth(alpha = 0.01, color = "black") +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dashed", size = 1) + 
  labs(y = "Proportion", color = "Iterations", title = "Iterations of one run") 

epi_qual_plot
```