---
title: "TAT_rep"
author: "Victor Møller"
date: "19 maj 2019"
output: html_document
---

set-up

```{r}
#set working directory
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv")

#packages 
library(pacman)
p_load(tidyverse, ggunchained) 
```

loading data. 

```{r}

#reading 
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/"

files <- list.files(path = path, pattern="*.csv") #if possible. 

mycols <- c("replica", 
            "turn", 
            "studies", 
            "network", 
            "population", 
            "sigma",
            "sample_size",
            "true_model",
            "strategy",
            "edges_replication_study",
            "edges_replicated",
            "proportion_true")

#loading them 
dfList <- lapply(files, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
df <- do.call(rbind, dfList) 
rm(dfList)
```

Replication.
Consider removing some items (I.e., runs with less than 10 replication studies in total).

```{r}

#replication rate & time at true model
summary <- df %>%
  filter(edges_replication_study >= 1) %>% #does not change matters. 
  group_by(replica, network, population, sigma, true_model) %>%
  summarize(RR = sum(edges_replicated) / sum(edges_replication_study),
            TAT = mean(proportion_true),
            RR_n = sum(edges_replication_study)) 

RR$network <- as.factor(RR$network)

#what in the world?


```

Start plotting. 

```{r}

#all models 
g <- summary %>% 
  ggplot(aes(TAT, RR, color = population)) +
      geom_point(aes(shape = network)) +
      scale_color_discrete(name = "Population") +
      labs(title = "Replication rate & time at true model", y = "Replication rate",
       x = "Time at true model") +
      geom_smooth(method = "lm", se = FALSE) +
      theme_janco_point()

g

#model 2
g1 <- summary %>%
  filter(true_model == 2) %>%
    ggplot(aes(TAT, RR, color = population)) +
      geom_point(aes(shape = network)) +
      scale_color_discrete(name = "Population") +
      labs(title = "Replication rate & time at true model", y = "Replication rate",
       x = "Time at true model") +
      geom_smooth(method = "lm", se = FALSE) +
      theme_janco_point()

g1

#model 7
g2 <- summary %>%
  filter(true_model == 7) %>%
    ggplot(aes(TAT, RR, color = population)) +
      geom_point(aes(shape = network)) +
      scale_color_discrete(name = "Population") +
      labs(title = "Replication rate & time at true model", y = "Replication rate",
       x = "Time at true model") +
      geom_smooth(method = "lm", se = FALSE) +
      theme_janco_point()

g2

#model 13
g3 <- summary %>%
  filter(true_model == 13) %>%
    ggplot(aes(TAT, RR, color = population)) +
      geom_point(aes(shape = network)) +
      scale_color_discrete(name = "Population") +
      labs(title = "Replication rate & time at true model", y = "Replication rate",
       x = "Time at true model") +
      geom_smooth(method = "lm", se = FALSE) +
      theme_janco_point()

g3


```

