---
title: "network"
author: "Victor Møller"
date: "2 apr 2019"
output: html_document
---

```{r setup, include=FALSE}

library(pacman)
p_load(tidyverse, igraph)

```

http://kateto.net/networks-r-igraph

```{r}
m <- rep(1,20)
dim(m) <- c(5,4)
m <- matrix(data=1, nrow=5, ncol=4)

#combining vectors to matrix
m <- cbind(1:5, 5:1, 5:9)
m <- rbind(1:5, 5:1, 5:9)

#dataframe
dfr1 <- data.frame( ID=1:4,
                    FirstName=c("John","Jim","Jane","Jill"),
                    Female=c(F,F,T,T), 
                    Age=c(22,33,44,55) )
```

flow control / loops 

```{r}
x <- 5; y <- 10
if (x==0) y <- 0 else y <- y/x #  
y

ASum <- 0; AProd <- 1
for (i in 1:x)  
{
  ASum <- ASum + i
  AProd <- AProd * i
}
ASum

```

network graphs

```{r}

g1 <- graph( edges=c(1,2, 2,3, 3, 1), n=3, directed=F ) 
plot(g1) 

g2 <- graph( edges=c(1,2, 2,3, 3, 1), n=10 )
plot(g2) 

g3 <- graph( c("John", "Jim", "Jim", "Jill", "Jill", "John"))
plot(g3)

g4 <- graph( c("John", "Jim", "Jim", "Jack", "Jim", "Jack", "John", "John"), 
             isolates=c("Jesse", "Janis", "Jennifer", "Justin") )  

#getting stuff out. 
E(g4) #edges
V(g4) #vertices (nodes)
g4[] #connections. 



```

graphs 

```{r}
#empty graph
eg <- make_empty_graph(40) #40 dots. 
plot(eg, vertex.size=10, vertex.label=NA) #vertex = dots. 

#full graph
fg <- make_full_graph(40)
plot(fg, vertex.size=10, vertex.label=NA)

#star graph
st <- make_star(40)
plot(st, vertex.size=10, vertex.label=NA) 

#small world 
tr <- make_tree(40, children = 3, mode = "undirected")
plot(tr, vertex.size=10, vertex.label=NA) 

#lattice?
rn <- make_ring(40)
plot(rn, vertex.size=10, vertex.label=NA)

```

random graph model

```{r}
#Erdos-Renyi 
er <- sample_gnm(n=100, m=400) 
plot(er, vertex.size=6, vertex.label=NA)  

#Watts-Strogatz 
sw <- sample_smallworld(dim=2, size=10, nei=1, p=0.1)
plot(sw, vertex.size=6, vertex.label=NA, layout=layout_in_circle)

#Barabasi-Albert 
ba <-  sample_pa(n=100, power=1, m=1,  directed=F)
plot(ba, vertex.size=6, vertex.label=NA)

#Zachary
zach <- graph("Zachary") # the Zachary carate club
plot(zach, vertex.size=10, vertex.label=NA)
```

loading data

```{r}
nodes <- read.csv("Dataset1-Media-Example-NODES.csv", header=T, as.is=T)
links <- read.csv("Dataset1-Media-Example-EDGES.csv", header=T, as.is=T)

head(nodes)
head(links)

nrow(nodes); length(unique(nodes$id))
nrow(links); nrow(unique(links[,c("from", "to")]))

#summing weight if > 1 connection between two nodes. 
links <- aggregate(links[,3], links[,-3], sum)


```

