---
title: "Untitled"
author: "Victor Møller"
date: "19 maj 2019"
output: html_document
---


```{r setup, include=FALSE}

#working directory 
setwd("~/CRUST-1/MetascienceBA/connectivity/KableTable")

#libraries
library(pacman)
p_load(knitr, kableExtra, tidyverse, tibble, rlang)

#clearing & reading 
temp <- list.files(pattern="*POP")
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ","))

#making rownames
a <- data.frame(name=c("Proportion at the true model",  
                      "50% at the true model",
                      "True model most popular",
                      "Stickiness of the true model",
                      "First passage time to true model",
                      "Replication rate",
                      "Replication rate of the true model"), 
                b=1:7,
                c=1:7,
                d=1:7)

```

organizing median. 

```{r}

medianFX <- function(.df, .ID, .measure){
  
  ID <- enquo(.ID)
  measure <- enquo(.measure)
  
  df <- .df %>%
    select(!!ID, !!measure) %>%
    mutate(!!measure := round(!!measure*100,2)) %>%
    spread(!!ID, !!measure)
  
  return(df)
  
}

TAT_MED <- medianFX(TAT_POP.csv, population, TAT_median)
TAT50_MED <- medianFX(TAT50_POP.csv, population, TAT50_median)
TATC_MED <- medianFX(TATC_POP.csv, population, TAT_median)
STICK_MED <- medianFX(STICK_POP.csv, population, stickiness_median)
RR_MED <- medianFX(RR_POP.csv, population, RR_median)
RRT_MED <- medianFX(RR_TF_POP.csv, population, RR_median)

#first passage (differs, so hard coded)
FPTT_MED <- FPTT_POP.csv %>%
  select(population, FPTT_median) %>%
  spread(population, FPTT_median)

#rbinding 
OutMed <- rbind(TAT_MED, #time at true most adhered
                   TAT50_MED,
                   TATC_MED,
                   STICK_MED,
                   FPTT_MED,
                   RR_MED,
                   RRT_MED) #time at true > 50 %

#new rownames 
rownames(OutMed) <- a$name

#kable - too much space 
OutMed %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      "hover", 
                                      "condensed", 
                                      "responsive"),
                full_width = F) %>%
  add_header_above(c("", "Median" = 4))

```

clearing environment

```{r}

rm(list=setdiff(ls(), c("a", "temp", "OutMed")))
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ","))

```

organizing IQR 

```{r}

#reusing the functon 
TAT_IQR <- medianFX(TAT_POP.csv, population, TAT_IQR)
TAT50_IQR <- medianFX(TAT50_POP.csv, population, TAT50_IQR)
TATC_IQR <- medianFX(TATC_POP.csv, population, TAT_IQR)
STICK_IQR <- medianFX(STICK_POP.csv, population, stickiness_IQR)
RR_IQR <- medianFX(RR_POP.csv, population, RR_IQR)
RRT_IQR <- medianFX(RR_TF_POP.csv, population, RR_IQR)

#first passage (differs, so hard coded)
FPTT_IQR <- FPTT_POP.csv %>%
  select(population, FPTT_IQR) %>%
  spread(population, FPTT_IQR)

#rbinding 
OutIQR <- rbind(TAT_IQR, #time at true most adhered
                   TAT50_IQR,
                   TATC_IQR,
                   STICK_IQR,
                   FPTT_IQR,
                   RR_IQR,
                   RRT_IQR) #time at true > 50 %

#new rownames 
rownames(OutIQR) <- a$name

```

clearing environment

```{r}

rm(list=setdiff(ls(), c("a", "temp", "OutMed", "OutIQR")))

```

Kable

```{r}

#creating the relevant groups 
MedIQR <- cbind(OutMed, OutIQR)
MedIQR <- add_column(MedIQR, " " = "", .after = 4)

#now we have to rename columns 
MedIQR <- MedIQR %>%
  rename(All = "All.1",
         Bo = "Bo.1",
         Mave = "Mave.1",
         Tess = "Tess.1")

#kable - median & IQR
MedIQR %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      #"hover", 
                                      #"condensed", 
                                      "responsive")) %>%
  add_header_above(c("", "Median" = 4, " " = 1, "IQR" = 4)) %>%
  add_header_above(c(" ", "Outcome Values for Populations" = 9)) #%>%
  #add_indent(c(2, 5)) 

#kable mean & IQR
MedIQR %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      #"hover", 
                                      #"condensed", 
                                      "responsive")) %>%
  add_header_above(c("", "Mean" = 4," " = 1, "IQR" = 4)) %>%
  add_header_above(c("", "Outcome Values for Populations" = 9)) #%>%
  #add_indent(c(2, 5)) 

```


plotting can get more crazy. 
https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

```{r}

#plot for another time 
lattice_mean %>%
  mutate(
    measures = rownames(.),
    Bo = cell_spec(Bo, "html", color = "red"),
    Mave = cell_spec(Mave, "html", color = "blue"),
    Tess = cell_spec(Tess, "html", color = "green"),
    All = cell_spec(All, "html", color = "purple")) %>%
  select(measures, Bo, Mave, Tess, All) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)

#footnote
  #footnote(general = "Here is a general comments of the table. ", #we can add notes. 
           #number = c("Footnote 1; ", "Footnote 2; "),
           #alphabet = c("Footnote A; ", "Footnote B; "),
           #symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
           #general_title = "General: ", number_title = "Type I: ",
           #alphabet_title = "Type II: ", symbol_title = "Type III: ",
           #footnote_as_chunk = T, title_format = c("italic", "underline")
           #)

```

