---
title: "Untitled"
author: "Mikkel Werling"
date: "2019 M04 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(pacman)
p_load(igraph, stringr, ggraph, wesanderson, cowplot, reshape)

```

reading all the parameter-files:

```{r}
setwd("~/CRUST-1/data/ABMdata/ABMrds/Sample_size_100/ABMrds2")

#readRDS

temp = list.files(pattern="*.rds")

#all in one
lattice_7 = lapply(temp[1:12], readRDS)

small_7 = lapply(temp[13:24], readRDS)
```

getting the clustering coefficient for the two networks

```{r}

cluster_lattice <- as.data.frame(NULL)

for(runs in 1:12){
  for (each in 1:50){
cluster_lattice[each, runs] <- lattice_7[[runs]][[each]][[11]]
  }
}

cluster_small <- as.data.frame(NULL)

for(runs in 1:12){
  for (each in 1:50){
cluster_small[each, runs] <- small_7[[runs]][[each]][[11]]
  }
}

cluster_lattice_melt <- melt(cluster_lattice)
cluster_small_melt <- melt(cluster_small)

#average path length

avglength_small <- as.data.frame(NULL)

for(runs in 1:12){
  for (each in 1:50){
avglength_small[each, runs] <- small_7[[runs]][[each]][[10]]
  }
}

avglength_lattice <- as.data.frame(NULL)

for(runs in 1:12){
  for (each in 1:50){
avglength_lattice[each, runs] <- lattice_7[[runs]][[each]][[10]]
  }
}

avglength_lattice_melt <- melt(avglength_lattice)
avglength_small_melt <- melt(avglength_small)

```

getting the cluster coefficient and average path length for small_
t-test for the two networks:

```{r}

t.test(avglength_lattice_melt$value, avglength_small_melt$value)
t.test(cluster_lattice_melt$value, cluster_small_melt$value)

```