---
title: "firstpassage"
author: "Victor Møller"
date: "18 maj 2019"
output: html_document
---

first passage time to 50%

```{r}
getwd()
#reading
mave02 <- read.csv("small_mave_0.2_BIC_100_hard_100.csv", sep = ";")

#plots.  
library(tidyverse)
library(reshape2)

#setting the true proportion col 
mave02 <- mave02 %>%
  mutate(proportion_true = proportion_7) #set the true model as PropTrue

#replication overall 
mave_overall <- mave02 %>%
  group_by(replica) %>%
  summarize(mean = min(which(proportion_true > 0.5))) %>%
  mutate(index = "index")

#getting median & IQR
mave_medianIQR <- mave_overall %>%
  group_by(index) %>%
  summarize(median = median(mean),
            IQR = IQR(mean))

```

first passage to most adhered to. 

```{r}

#checking - only gives the first replica - does not loop over replica
mave_sum <- mave02 %>%
  group_by(replica) %>%
  summarize(fpttt1 = min(which(15 == max.col(.[,c(25:38,47)], #or mave02
                         ties.method = "last"))))

#the code which runs shit. 
min(which(15 == max.col(mave02[,c(25:38,47)],
                        ties.method = "last"))) #so if equal to or greater than

#trying a subset 
mave5 <- mave02 %>%
  subset(replica == 5) %>%
  mutate(fpttt1 = min(which(15 == max.col(.[,c(25:38,47)],
                        ties.method = "last"))))

#loop 
replica <- 50
fpttt1 <- list()

for (rep in 1:replica){
  max[rep] <- max(mave02$proportion_true[rep])
  return(max)
}

d[,2:length(d)]
replica <- 50
rep <- 50

for (rep in mave02){
  mave02[rep] <- mave02 %>%
    subset(replica == rep) %>%
    
  fpttt1[rep] <- min(which(15 == max.col(mave02[,c(25:38,47)],
                        ties.method = "last")))
  return(fpttt1)
}

#jan something. 
mave_ratata <- mave02 %>%
  rownames_to_column() %>%
  group_by(replica) %>%
  summarize_at(vars(c(25:38,47)))

#jan something 


#with apply maybe or later, fucked. 
min(which("proportion_7" == colnames(mave02[,25:38])[apply(mave02,1,which.max)]))

```

