---
title: "Untitled"
author: "Victor Møller"
date: "19 maj 2019"
output: html_document
---


```{r setup, include=FALSE}

#working directory 
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/connectivity/outcome_results/sample_size_100")

#libraries
library(pacman)
p_load(knitr, kableExtra, tidyverse)

#clearing & reading 
temp <- list.files(pattern="lattice")
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ","))

#making rownames
a <- data.frame(name=c("Proportion of time at true model",  
                      "Proportion of time at true model > 50%",
                      "Stickiness of true model",
                      "Replication rate",
                      "Replication rate of the true model"), 
                b=1:5,
                c=1:5,
                d=1:5)

```

organizing lattice world median.

```{r}

#TAT
TAT_median_100 <- TAT_lattice_100.csv %>%
  select(population, TAT_median) %>% 
  spread(population, TAT_median) 

#TAT 50
TAT50_median_100 <- TAT50_lattice_100.csv %>%
  select(population, TAT50_median) %>%
  spread(population, TAT50_median)

#stickiness 
stickiness_median_100 <- stickiness_lattice_100.csv %>%
  select(population, stickiness_median) %>%
  spread(population, stickiness_median)

#replication rate overall
RR_median_100 <- RR_lattice_100.csv %>%
  select(population, RR_median) %>%
  spread(population, RR_median)

#replication rate true
RRT_median_100 <- RRT_lattice_100.csv %>%
  select(population, RR_true_median) %>%
  spread(population, RR_true_median)

#rbinding 
lattice_median <- rbind(TAT_median_100, #time at true most adhered
                   TAT50_median_100,
                   stickiness_median_100,
                   RR_median_100,
                   RRT_median_100) #time at true > 50 %

#times 100
lattice_median <- lattice_median %>%
  mutate(Bo = round(Bo*100, 2),
         All = round(All*100, 2),
         Mave = round(Mave*100, 2),
         Tess = round(Tess*100, 2)) 

#new rownames 
rownames(lattice_median) <- a$name

#kable - too much space 
lattice_median %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      "hover", 
                                      "condensed", 
                                      "responsive"),
                full_width = F) %>%
  add_header_above(c("", "Lattice & Median" = 4))

```

clearing environment

```{r}

rm(list=setdiff(ls(), c("a", "temp", "lattice_median")))
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ","))

```

organizing lattice world & mean. 

```{r}
#TAT
TAT_mean_100 <- TAT_lattice_100.csv %>%
  select(population, TAT_mean) %>% 
  spread(population, TAT_mean) 

#TAT 50
TAT50_mean_100 <- TAT50_lattice_100.csv %>%
  select(population, TAT50_mean) %>%
  spread(population, TAT50_mean)

#stickiness 
stickiness_mean_100 <- stickiness_lattice_100.csv %>%
  select(population, stickiness_mean) %>%
  spread(population, stickiness_mean)

#replication rate overall
RR_mean_100 <- RR_lattice_100.csv %>%
  select(population, RR_mean) %>%
  spread(population, RR_mean)

#replication rate true
RRT_mean_100 <- RRT_lattice_100.csv %>%
  select(population, RR_true_mean) %>%
  spread(population, RR_true_mean)

#rbinding 
lattice_mean <- rbind(TAT_mean_100, #time at true 
                   TAT50_mean_100,
                   stickiness_mean_100,
                   RR_mean_100,
                   RRT_mean_100) #time at true > 50 %

#times 100
lattice_mean <- lattice_mean %>%
  mutate(Bo = round(Bo*100, 2),
         All = round(All*100, 2),
         Mave = round(Mave*100, 2),
         Tess = round(Tess*100, 2)) 

#new rownames 
rownames(lattice_mean) <- a$name

```

clearing environment

```{r}

rm(list=setdiff(ls(), c("a", "temp", "lattice_median", "lattice_mean")))
for(i in 1:length(temp)) assign(temp[i], read.csv(temp[i], sep = ","))

```

organizing lattice world & IQR

```{r}
#TAT
TAT_IQR_100 <- TAT_lattice_100.csv %>%
  select(population, TAT_IQR) %>% 
  spread(population, TAT_IQR) 

#TAT 50
TAT50_IQR_100 <- TAT50_lattice_100.csv %>%
  select(population, TAT50_IQR) %>%
  spread(population, TAT50_IQR)

#stickiness 
stickiness_IQR_100 <- stickiness_lattice_100.csv %>%
  select(population, stickiness_IQR) %>%
  spread(population, stickiness_IQR)

#replication rate overall
RR_IQR_100 <- RR_lattice_100.csv %>%
  select(population, RR_IQR) %>%
  spread(population, RR_IQR)

#replication rate true
RRT_IQR_100 <- RRT_lattice_100.csv %>%
  select(population, RR_true_IQR) %>%
  spread(population, RR_true_IQR)

#rbinding 
lattice_IQR <- rbind(TAT_IQR_100, #time at true 
                   TAT50_IQR_100,
                   stickiness_IQR_100,
                   RR_IQR_100,
                   RRT_IQR_100) #time at true > 50 %

#times 100
lattice_IQR <- lattice_IQR %>%
  mutate(Bo = round(Bo*100, 2),
         All = round(All*100, 2),
         Mave = round(Mave*100, 2),
         Tess = round(Tess*100, 2)) 

#new rownames 
rownames(lattice_IQR) <- a$name

```

clearing environment

```{r}

rm(list=setdiff(ls(), c("a", "temp", "lattice_median", "lattice_mean", "lattice_IQR")))

```

Kable

```{r}
library(tibble)
dataset <- data.frame(a = 1:5, b = 2:6, c=3:7)
add_column(dataset, d = 4:8, .after = 2)

#creating the relevant groups 
lattice_median_IQR <- cbind(lattice_median, lattice_IQR)
lattice_mean_IQR <- cbind(lattice_mean, lattice_IQR)

lattice_median_IQR <- add_column(lattice_median_IQR, " " = "", .after = 4)
lattice_mean_IQR <- add_column(lattice_mean_IQR, " " = "", .after = 4)
#now we have to rename columns 
lattice_median_IQR <- lattice_median_IQR %>%
  rename(All = "All.1",
         Bo = "Bo.1",
         Mave = "Mave.1",
         Tess = "Tess.1")

lattice_mean_IQR <- lattice_mean_IQR %>%
  rename(All = "All.1",
         Bo = "Bo.1",
         Mave = "Mave.1",
         Tess = "Tess.1")

#kable - median & IQR
lattice_median_IQR %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      #"hover", 
                                      #"condensed", 
                                      "responsive")) %>%
  add_header_above(c("", "Median" = 4, " " = 1, "IQR" = 4)) %>%
  add_header_above(c(" ", "Lattice" = 9)) #%>%
  #add_indent(c(2, 5)) 

#kable mean & IQR
lattice_mean_IQR %>%
  kable() %>%
  kable_styling(bootstrap_options = c("striped", 
                                      #"hover", 
                                      #"condensed", 
                                      "responsive")) %>%
  add_header_above(c("", "Mean" = 4," " = 1, "IQR" = 4)) %>%
  add_header_above(c("", "Lattice" = 9)) #%>%
  #add_indent(c(2, 5)) 

```


plotting can get more crazy. 
https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html

```{r}

#plot for another time 
lattice_mean %>%
  mutate(
    measures = rownames(.),
    Bo = cell_spec(Bo, "html", color = "red"),
    Mave = cell_spec(Mave, "html", color = "blue"),
    Tess = cell_spec(Tess, "html", color = "green"),
    All = cell_spec(All, "html", color = "purple")) %>%
  select(measures, Bo, Mave, Tess, All) %>%
  kable(format = "html", escape = F) %>%
  kable_styling("striped", full_width = F)

#footnote
  #footnote(general = "Here is a general comments of the table. ", #we can add notes. 
           #number = c("Footnote 1; ", "Footnote 2; "),
           #alphabet = c("Footnote A; ", "Footnote B; "),
           #symbol = c("Footnote Symbol 1; ", "Footnote Symbol 2"),
           #general_title = "General: ", number_title = "Type I: ",
           #alphabet_title = "Type II: ", symbol_title = "Type III: ",
           #footnote_as_chunk = T, title_format = c("italic", "underline")
           #)

```

