---
title: "replication scaled"
author: "Victor Møller"
date: "19 maj 2019"
output: html_document
---

```{r}
#set working directory
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv")

#packages 
library(pacman)
p_load(tidyverse, ggunchained) 
```

loading data. 

```{r}

#reading 
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/"

files <- list.files(path = path, pattern="*.csv") #if possible. 

mycols <- c("replica", 
            "network", 
            "population", 
            "sigma",
            "true_model",
            "edges_replication_study",
            "edges_replicated",
            "final_global_true_model")

#loading them 
dfList <- lapply(files, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
df <- do.call(rbind, dfList) 
rm(dfList)
```

replication overall 

```{r}

#replication overall 
df_overall <- df %>%
  group_by(replica, network, population, sigma, true_model) %>%
  summarize(replicated = sum(edges_replicated) / sum(edges_replication_study)) 

```

overall summary stats

```{r}
#summary stats
df_overall_sum <- df_overall %>%
  group_by(network, population) %>%
  summarize(RR_median = median(replicated),
            RR_mean = mean(replicated),
            RR_IQR = IQR(replicated)) 
  #mutate(final_global_true_model = "all cases")
```

by global

```{r}
#replication if true & if not
df_byglobal <- df %>%
  group_by(final_global_true_model, replica, network, population, true_model) %>%
  summarize(replicated = sum(edges_replicated) / sum(edges_replication_study)) 
```

lattice summary stats by global 

```{r}
#replicated if true & if not (median & IQR)
df_byglobal_sum <- df_byglobal %>%
  group_by(final_global_true_model, network, population) %>%
  summarize(RR_true_median = median(replicated, na.rm = TRUE),
            RR_true_mean = mean(replicated, na.rm = TRUE),
            RR_true_IQR = IQR(replicated, na.rm = TRUE)) %>%
  ungroup()

#only true 
df_true_sum <- df_byglobal_sum %>%
  subset(final_global_true_model == 1) %>%
  select(network, population, RR_true_median, RR_true_IQR, RR_true_mean)

```

relevant subsets 

```{r}

RR_lattice_100 <- df_overall_sum %>%
  filter(network == "Lattice") %>%
  select(network, population, RR_median, RR_mean, RR_IQR)

RR_small_100 <- df_overall_sum %>%
  filter(network == "Small") %>%
  select(network, population, RR_median, RR_mean, RR_IQR)

RRT_lattice_100 <- df_true_sum %>%
  filter(network == "Lattice") %>%
  select(network, population, RR_true_median, RR_true_mean, RR_true_IQR)
    
RRT_small_100 <- df_true_sum %>%
  filter(network == "Small") %>%
  select(network, population, RR_true_median, RR_true_mean, RR_true_IQR)

#checking 
head(RR_lattice_100)
head(RR_small_100)
head(RRT_lattice_100)
head(RRT_small_100)

```

write.csv

```{r}
#working directory 
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/connectivity/outcome_results")

#writing csv. 
write.csv(RR_lattice_100, "RR_lattice_100.csv", row.names = F)
write.csv(RR_small_100, "RR_small_100.csv", row.names = F)
write.csv(RRT_lattice_100, "RRT_lattice_100.csv", row.names = F)
write.csv(RRT_small_100, "RRT_small_100.csv", row.names = F)

#testing 
RR_lattice_100 <- read.csv("RR_lattice_100.csv")
RR_small_100 <- read.csv("RR_small_100.csv")
RRT_lattice_100 <- read.csv("RRT_lattice_100.csv")
RRT_small_100 <- read.csv("RRT_small_100.csv")

#testing 
head(RR_lattice_100)
head(RR_small_100)
head(RRT_lattice_100)
head(RRT_small_100)

```
