---
title: "TAT_TAT50"
author: "Victor Møller"
date: "26 maj 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("~/CRUST-1/data/tests")

library(tidyverse)

```

loading data. 

```{r}

#reading 
path <- "~/CRUST-1/data/tests/"

files <- list.files(path = path, pattern="*csv") #if possible. 

#taken from the scatter-plot file (reconsider what is needed)
mycols <- c("replica", 
            "network", 
            "population", 
            "sigma",
            "net_size",
            "colab_cond",
            "true_model",
            "base_SS",
            "prop_true")

#loading them 
dfList <- lapply(files, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
df <- do.call(rbind, dfList) 
rm(dfList)
```

Calculating TAT (total time)
Not grouped by sigma (could be revised).
NB: proportion needs to be set to the true model (in this case 7). 

```{r}

#TAT PER REPLICA
TAT <- df %>%  
  mutate(TAT_50 = ifelse(prop_true >= 0.5, 1, 0)) %>%
  group_by(replica, network, population, true_model, sigma, net_size, 
           base_SS, colab_cond) %>% 
  summarise(TAT = mean(prop_true),
            TAT50 = mean(TAT_50)) 

#TAT AVG. OVER REP. 
TAT <- df %>%  
  mutate(TAT_50 = ifelse(prop_true >= 0.5, 1, 0)) %>%
  group_by(network, population, true_model, sigma, net_size, 
           base_SS, colab_cond) %>% 
  summarise(TAT = mean(prop_true),
            TAT50 = mean(TAT_50)) 



```

relevant subsets 

```{r}

#NETWORK & POP
TAT_sum <- TAT %>%
  group_by(network, population) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = mean(TAT50),
            TAT50_IQR = IQR(TAT50))

#SIGMA
TAT_sum1 <- TAT %>%
  group_by(sigma) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = round(mean(TAT50),2),
            TAT50_IQR = IQR(TAT50))


```


write csv 

```{r}
#new working directory 
setwd("~/CRUST-1/connectivity/outcome_results")
      
#write csv
write.csv(TAT_lattice_100, "TAT_lattice_100.csv", row.names = FALSE)
write.csv(TAT_small_100, "TAT_small_100.csv", row.names = FALSE)
write.csv(TAT50_lattice_100, "TAT50_lattice_100.csv", row.names = FALSE)
write.csv(TAT50_small_100, "TAT50_small_100.csv", row.names = FALSE)

```

