---
title: "TAT_TAT50"
author: "Victor Møller"
date: "26 maj 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv")

library(tidyverse)

```

loading data. 

```{r}

#reading 
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/"

files <- list.files(path = path, pattern="*csv") #if possible. 

#taken from the scatter-plot file (reconsider what is needed)
mycols <- c("replica", 
            "network", 
            "population", 
            "sigma",
            "true_model",
            "proportion_true")

#loading them 
dfList <- lapply(files, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
df <- do.call(rbind, dfList) 
rm(dfList)
```

Calculating TAT (total time)
Not grouped by sigma (could be revised).
NB: proportion needs to be set to the true model (in this case 7). 

```{r}

#TAT
TAT <- df %>%  #set the true model
  mutate(TAT_50 = ifelse(proportion_true >= 0.5, 1, 0)) %>%
  group_by(replica, network, population, true_model, sigma) %>% 
  summarise(TAT = mean(proportion_true),
            TAT50 = mean(TAT_50)) 

#TAT summarizized
TAT_sum <- TAT %>%
  group_by(network, population) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = mean(TAT50),
            TAT50_IQR = IQR(TAT50))

```

write csv 

```{r}
#new working directory 
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/connectivity/outcome_results"
      
#write csv
write.csv(TAT_sum, "TAT_TAT50.csv", row.names = FALSE)

```

