---
title: "extensiontime14models"
author: "Victor Møller"
date: "14 maj 2019"
output: html_document
---

Run the first part of howlongcanyougo (I.e., the setup.)
Then you can initialize the instructor. 

```{r}

decapitator <- function(replications, timesteps, models, k, 
    weights, sampleSize, correlation, sigma,
    modelCompare, modelSelection, inputDir, outputDir, outputFile, paramFile,
    verbose, ndec, seeds, some_models){

## REPLICA SIMULATION
  ###################
  parameters <- list()
  for(replica in 1:replications){
    set.seed(seeds[replica])

    ## Select randomly Global Model and previous Global Model
    # Sampling / randomizing stuff. 
    V(g)$type <- sample(c("Bo", "Mave", "Tess"))
    V(g)$type <- sample(V(g)$type)
    V(g)$name <- make.unique(V(g)$type) 
    V(g)$model <- sample(some_models)
    V(g)$model <- sample(V(g)$model)
    matrix_g <- as_adjacency_matrix(g, sparse = F) 
    agentTurn <- sample(V(g)$name, size = 11000, replace = T) 
    
    ## Generate Xset and deterministic value of the linear regression
    trueModel <- some_models[replica]
    tModel <- strToModel(trueModel, k)
    Xset <- generateXSet(sampleSize, k, correlation)
    tModelBetas <- getBetas(tModel, weights, sigma)
    deterministic <- calculateDet(tModel, Xset, weights, tModelBetas)
    #######################
    ## OUTPUT PARAMETERS
    #######################
    output <- matrix(data=NA, nrow=timesteps, ncol=O_NUM_FIELDS)


    #######################
    ## SIMULATION EXECUTION
    #######################
step <- 1
#does it work?
for(step in 1:timesteps){ #11000 time-steps

      ## initialize parameters 
      changed <- 0 #for them to add in 
      tried <- 0 #for all elements in edges
      already <- 0 #for all the agents who already had the global
      rejector <- 0 #those that did not change bc. they shouldn't. 
  
      ## Select the token of agent
      agentToken <- agentTurn[step] 
      
      ## Agents 
      agentIndex <- which((V(g)$name) == agentToken)
      
      ## model & in format
      gModel <- strToModel(V(g)$model[agentIndex], k) #local model

      ## Tess
      if(V(g)$type[agentIndex] == "Tess"){ #detect
        model <- modelSimilarByTerm(gModel, models, mode="random",
                                    modelSelection=modelSelection)

      ## Mave
      } else if(V(g)$type[agentIndex] == "Mave"){
        model <- models[[as.integer(runif(1, min=1, max=length(models)+1))]]
        
      ## Bo is fucked. 
      } else if(V(g)$type[agentIndex] == "Bo"){
        model <- modelSimilarByInteraction(gModel, models, mode="random",
                                           modelSelection=modelSelection)
      }
      #setting up. 
      model1 <- model
      model2 <- gModel

      #adding variance & statistics for different engines (AIC, BIC)
  Yset <- generateY(deterministic, sigma) #putting variance on the deterministic.
  stat <- analysis(model, gModel, Yset, Xset, weights) #computing all the shit.
      
      #smooth -> should we switch
      switchModel <- FALSE
      if((modelCompare == TSTATISTICS) &
          (!is.null(stat$model$tstatistics)) &
          (!is.null(stat$gModel$tstatistics)) &
          (!is.na(stat$model$tstatistics)) &
          (!is.na(stat$gModel$tstatistics))){
        if(stat$model$tstatistics > stat$gModel$tstatistics){
          switchModel <- TRUE
        }
      } else if((modelCompare == RSQ) &
          (!is.null(stat$model$rsq)) &
          (!is.null(stat$gModel$rsq)) &
          (!is.na(stat$model$rsq)) &
          (!is.na(stat$gModel$rsq))){
        if(stat$model$rsq > stat$gModel$rsq){
          switchModel <- TRUE
        }
      } else if((modelCompare == AIC) &
          (!is.null(stat$model$aic)) &
          (!is.null(stat$gModel$aic)) &
          (!is.na(stat$model$aic)) &
          (!is.na(stat$gModel$aic))){
        if(stat$model$aic < stat$gModel$aic){
          switchModel <- TRUE
        }
      } else if((modelCompare == BIC) &
          (!is.null(stat$model$bic)) &
          (!is.null(stat$gModel$bic)) &
          (!is.na(stat$model$bic)) &
          (!is.na(stat$gModel$bic))){
        if(stat$model$bic < stat$gModel$bic){
          switchModel <- TRUE
        }
      } else if((modelCompare == ARSQ) &
          (!is.null(stat$model$arsq)) &
          (!is.null(stat$gModel$arsq)) &
          (!is.na(stat$model$arsq)) &
          (!is.na(stat$gModel$arsq))){
        if(stat$model$arsq > stat$gModel$arsq){
          switchModel <- TRUE
        }
      }
      
      #what do you do?
      initGModel <- gModel
      initGModelStat <- stat$gModel
      
      #changing global if TRUE (for recording)
      if(switchModel){
        #from the old. 
        gModel <- model
        finalGModelStat <- stat$model
        #local change of model
        modelStr <- modelToStr(gModel)
        modelStr <- str_replace(modelStr, "Y ~", "")
        modelStr <- str_replace_all(modelStr, ":", "")
        V(g)$model[agentIndex] <- modelStr
        
        #this ends the original agents turn
        } else {
        finalGModelStat <- stat$gModel
        }
        
      if(switchModel){
        #making ready for the loop. 
        edges <- names(which(matrix_g[, agentIndex] == 1)) #maybe. 
        
        #here goes for loop. 
        for(i in edges){
          
          ## tried 
          tried <- tried + 1
          
          ## which one 
          agentToken <- i
          
          ## Agents 
          agentIndex <- which((V(g)$name) == agentToken)
      
          ## model & in format
          gModel <- strToModel(V(g)$model[agentIndex], k) #just to call it else. 
          
          #adding variance & statistics for different engines (AIC, BIC)
          Yset <- generateY(deterministic, sigma) #putting variance on the                  deterministic.
          stat <- analysis(model, gModel, Yset, Xset, weights) #computing all the           shit.
          
          ## already at true model (atm). 
          atm <- as.numeric(compareModels(tModel, gModel))
          already <- already + atm
      
      #smooth -> should we switch
      switchModel1 <- FALSE
      if((modelCompare == TSTATISTICS) &
          (!is.null(stat$model$tstatistics)) &
          (!is.null(stat$gModel$tstatistics)) &
          (!is.na(stat$model$tstatistics)) &
          (!is.na(stat$gModel$tstatistics))){
        if(stat$model$tstatistics > stat$gModel$tstatistics){
          switchModel1 <- TRUE
        }
      } else if((modelCompare == RSQ) &
          (!is.null(stat$model$rsq)) &
          (!is.null(stat$gModel$rsq)) &
          (!is.na(stat$model$rsq)) &
          (!is.na(stat$gModel$rsq))){
        if(stat$model$rsq > stat$gModel$rsq){
          switchModel1 <- TRUE
        }
      } else if((modelCompare == AIC) &
          (!is.null(stat$model$aic)) &
          (!is.null(stat$gModel$aic)) &
          (!is.na(stat$model$aic)) &
          (!is.na(stat$gModel$aic))){
        if(stat$model$aic < stat$gModel$aic){
          switchModel1 <- TRUE
        }
      } else if((modelCompare == BIC) &
          (!is.null(stat$model$bic)) &
          (!is.null(stat$gModel$bic)) &
          (!is.na(stat$model$bic)) &
          (!is.na(stat$gModel$bic))){
        if(stat$model$bic < stat$gModel$bic){
          switchModel1 <- TRUE
        }
      } else if((modelCompare == ARSQ) &
          (!is.null(stat$model$arsq)) &
          (!is.null(stat$gModel$arsq)) &
          (!is.na(stat$model$arsq)) &
          (!is.na(stat$gModel$arsq))){
        if(stat$model$arsq > stat$gModel$arsq){
          switchModel1 <- TRUE
        }
      } else { 
        finalGModelStat <- stat$gModel
      }
      
      if(switchModel1){
        gModel <- model 
        #finalGModelStat <- stat$model
        modelStr <- modelToStr(gModel)
        modelStr <- str_replace(modelStr, "Y ~", "")
        modelStr <- str_replace_all(modelStr, ":", "")
        V(g)$model[agentIndex] <- modelStr
        changed <- changed + 1
        } #this ends the for loop ()
      
        #did they already have the global model?
      else if(compareModels(gModel, tModel)){
        rejector <- rejector + 1
        #did they just not change. 
      } else {
        finalGModelStat <- stat$gModel
      }
        }
      }

      ## Record output data (commenting fucked stuff)
      output[step, O_STRATEGY] <- V(g)$type[agentIndex] #new.
      output[step, O_SELECTED_MODEL] <- searchModel(model, models)
      output[step, O_SELECTED_TRUE_MODEL] <- as.numeric(compareModels(model, tModel))
      output[step, O_SELECTED_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, stat$model$betasEst), ndec)
      output[step, O_INITIAL_GLOBAL_MODEL] <- searchModel(initGModel, models)
      output[step, O_INITIAL_GLOBAL_TRUE_MODEL] <- as.numeric(compareModels(initGModel, tModel))
      output[step, O_INITIAL_GLOBAL_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, initGModelStat$betasEst), ndec)
      output[step, O_FINAL_GLOBAL_MODEL] <- searchModel(gModel, models)
      output[step, O_FINAL_GLOBAL_TRUE_MODEL] <- as.numeric(compareModels(gModel, tModel))
      output[step, O_FINAL_GLOBAL_MODEL_DISTANCE] <- round(calculateDistance(tModelBetas, finalGModelStat$betasEst), ndec)
      output[step, O_NUM_PREDICTORS] <- predictors[[1]][as.numeric(as.character(output[step, O_FINAL_GLOBAL_MODEL]))]
      output[step, O_SAMPLE_SIZE] <- sampleSize
      output[step, O_BETA1_TRUE] <- round(tModelBetas[,2], ndec)
      output[step, O_BETA1_ESTIMATE] <- round(finalGModelStat$betasEst[2], ndec)
      output[step, O_BETA1_ERROR] <- round(finalGModelStat$betasErr[2], ndec)
      output[step, O_TSTATISTICS] <- round(finalGModelStat$tstatistics, ndec)
      output[step, O_RSQ] <- round(finalGModelStat$rsq, ndec)
      output[step, O_ARSQ] <- round(finalGModelStat$arsq, ndec)
      output[step, O_AIC] <- round(finalGModelStat$aic, ndec)
      output[step, O_BIC] <- round(finalGModelStat$bic, ndec)
      output[step, O_AGENT_INDEX] <- V(g)$name[agentIndex] #new
      output[step, O_PREDICTORS] <- toString(predictors[[2]][as.numeric(as.character(output[step, O_FINAL_GLOBAL_MODEL]))])
      output[step, O_PROPORTION] <- mean(as.numeric(V(g)$model == trueModel)) #new
      output[step, O_TRIED] <- tried #new
      output[step, O_CHANGED] <- changed #new
      output[step, O_ALREADY] <- already #new
      output[step, O_REJECTOR] <- rejector #new
      output[step, O_SIGMA] <- sigma #new - and maybe dubious
      output[step, O_TRUEMOD] <- gsub(" ", "", substr(modelToStr(tModel), 5,
            nchar(modelToStr(tModel))), fixed=TRUE)
  }

## Parameter output
    param <- list()
    param[[P_TMODEL]] <- gsub(" ", "", substr(modelToStr(tModel), 5,
            nchar(modelToStr(tModel))), fixed=TRUE)
    param[[P_K]] <- k
    param[[P_SAMPLE_SIZE]] <- sampleSize
    param[[P_SIGMA]] <- sigma
    param[[P_CORRELATION]] <- correlation
    #param[[P_AGENT_WEIGHTS]] <- c(nRey, nTess, nBo, nMave) /
        #(nRey + nTess + nBo + nMave)
    param[[P_TRUE_BETAS]] <- tModelBetas
    param[[P_XSET]] <- Xset
    param[[P_NETWORK]] <- matrix_g
    parameters[[replica]] <- param
    

    ## Convert output matrix into data table
    output <- data.table(cbind(rep(replica, timesteps), 1:timesteps, output))
    names(output) <- OUTPUT_HEADER

    ## Write output data table into a file
    write.table(output, file=paste0(outputDir, "/", outputFile),
        append=ifelse(replica == 1, FALSE, TRUE),
        quote=FALSE, sep=";", row.names=FALSE,
        col.names=ifelse(replica == 1, TRUE, FALSE))
  }

  saveRDS(parameters, file=paste0(outputDir, "/", paramFile))
}

      
```

running the decapitator

```{r}

decapitator(replications, timesteps, models, k, 
    weights, sampleSize, correlation, sigma,
    modelCompare, modelSelection, inputDir, outputDir, outputFile, paramFile,
    verbose, ndec, seeds, some_models)

```

```{r}

m_all <- read.csv("data/small_epistemic_test/output_all.csv", sep = ";")

#proportion over time? 
ggplot(m_all, aes(timestep, proportion)) +
  geom_point() +
  geom_smooth() +
  geom_hline(data = IamGood, aes(yintercept = 0.5), color = "red", linetype = "dashed", size = 1) +
  facet_wrap(~true_model)

```

