---
title: "prep_BA_reworkLOOP"
author: "Victor Møller"
date: "November 14, 2019"
output: html_document
---
14-09-2019
This document tests & cleans data from ABM5. 
It is probably only going to work for test-phase with small
amounts of data. It takes data from "new_data" folder and outputs to "tests".

```{r}

#packages
library(pacman)
p_load(tidyverse, tidyselect, data.table)

```

First chunk is a screening of the data. 
Does it pass our sanity checks & do we have all cases? 

```{r}

#Working directory of RAW data. 
setwd("D:/Data from Computer Room/LATTICE")

#for basic tests
condition <- list()
network <- list()
population <- list()
sigma <- list()
base_SS <- list()
true_model <- list()
replica <- list()

#for other tests 
studiesMAX <- list()
studiesMIN <- list()
prop_true <- list()

#the masterlist
masterlist <- list()

#your files 
files = list.files(pattern=c("*.csv"), full.names=TRUE)

#running the function
dataload <- function(i){
  
  for(i in files){
    
  #reading data
  data <- read_csv(i)
  data <- na.omit(data)
  data <- tibble::as_tibble(data)
  
  #factorizing 
  data <- data %>%
  mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         net_size = factor(net_size),
         base_SS = factor(base_SS),
         true_model = factor(true_model),
         colab_cond = factor(colab_cond),
         orig_type = factor(orig_type),
         strategy = factor(strategy))
  
  #basic tests 
  condition[i] <- paste0(i)
  network[i] <- levels(data$network)
  population[i] <- levels(data$population)
  sigma[i] <- levels(data$sigma)
  base_SS[i] <- levels(data$base_SS)
  true_model[i] <- levels(data$true_model)
  replica[i] <- sum(unique(data$replica))
  
  #more tests 1: all replicas 10,000. 
  check <- data %>%
  group_by(replica, network, population, sigma, true_model,
           base_SS, net_size, colab_cond) %>%
  summarize(stud = max(studies))
  
  studiesMAX[i] <- min(check$stud) #10,000
  studiesMIN[i] <- max(check$stud) #10,000
  
  #more tests 2: true model = true model
  data2 <- i %>%
  filter(true_model == paste0(i$true_model[1]))
  prop_true[i] <- all(data2$prop_2 == data2$prop_true)
  
  
  }
  
  masterlist <- list(network, population, sigma, base_SS,
                     true_model, replica, studiesMAX, studiesMIN,
                     prop_true)
  return(masterlist)
  
}

test <- dataload(files)

## taking out parameters 
network <- unname(unlist(test[[1]]))
population <- unname(unlist(test[[2]]))
sigma <- unname(unlist(test[[3]]))
base_SS <- unname(unlist(test[[4]]))
true_model <- unname(unlist(test[[5]]))
replica <- unname(unlist(test[[6]]))
studiesMAX <- unname(unlist(test[[7]]))
studiesMIN <- unname(unlist(test[[8]]))



```

data preparation for "violin_extended_rework": 

```{r}

#working directory. 
setwd("E:/data_prepped")
path = "E:/data_prepped/"
files <- list.files(path = path, pattern="*.csv")

#initializing empty list 
datalist <- list()

violin_extended_rework <- function(files){
  
  #selecting cols (check )
    mycols <- c("replica", 
            "turn", 
            "studies", 
            "network", 
            "population", 
            "sigma",
            "base_SS",
            "colab_cond",
            "net_size",
            "true_model",
            "strategy",
            "switch_rep_study",
            "switch_rep",
            "prop_true",
            "prop_t_mod")
  
  for(i in files){

    #read csv 
    df <- read_csv(i)[mycols]
    
    #as factor
    df <- df %>%
    mutate(network = factor(network),
          population = factor(population),
          sigma = factor(sigma),
          base_SS = factor(base_SS),
          colab_cond = factor(colab_cond),
          net_size = factor(net_size),
          true_model = factor(true_model),
          strategy = factor(strategy))
    
    #create DF. 
    df <- df %>%
        group_by(replica, network, population, sigma, true_model,
           base_SS, net_size, colab_cond) %>%
        summarize(RR = sum(switch_rep) / 
              sum(switch_rep_study)) 
    
    datalist[i] <- list(df)
  }
    
  df_final <- do.call("rbind", datalist)
  return(df_final)
}

```


