---
title: "some_models"
author: "Mikkel Werling"
date: "5/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}

library(pacman)
p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, rlist, nnet)
```

paths

```{r}
#setwd("~/CRUST-1/connectivity/loads")
baseDir <- "."
scriptDir <- paste0(baseDir, "/FunctionsLoads/Functions")
#inputDir <- paste0(baseDir, "/DevezerAlteredAgents/data")
#outputDir <- paste0(baseDir, "/DevezerAlteredAgents/data/raw")
```

functions

```{r}
source(paste0(scriptDir, "/analysis.R"))
source(paste0(scriptDir, "/calculateDet.R"))
source(paste0(scriptDir, "/calculateDistance.R"))
source(paste0(scriptDir, "/compareModels.R"))
source(paste0(scriptDir, "/constants.R"))
source(paste0(scriptDir, "/convertBinary.R"))
source(paste0(scriptDir, "/generateBetas.R"))
source(paste0(scriptDir, "/generateModels.R"))
source(paste0(scriptDir, "/generateXSet.R"))
source(paste0(scriptDir, "/generateY.R"))
source(paste0(scriptDir, "/getBetas.R"))
source(paste0(scriptDir, "/getPredictors.R"))
source(paste0(scriptDir, "/modelSimilarByInteraction.R"))
source(paste0(scriptDir, "/modelSimilarByTerm.R"))
source(paste0(scriptDir, "/modelToStr.R"))
source(paste0(scriptDir, "/searchModel.R"))
source(paste0(scriptDir, "/seedGenerator.R"))
source(paste0(scriptDir, "/simulator.R"))
source(paste0(scriptDir, "/strToModel.R"))
```

Generating models for Devezer. 
Fixes the fact that models 10 & 14 are switched around in their code.  

```{r}

#fixing their mistake with model 10 being rep. as model 14.  
models2 <- generateModels(k = 3)
models <- models2
models[c(10:13)] = models2[c(11:14)]
models[[14]] <- models2[[10]]

#write devezer model
outputDir <- paste0(baseDir, "/FunctionsLoads/Loads/DevezerLoads")
save(models, file = paste0(outputDir, "/models"))
```

Generating models for MetascienceBa. 
Some formatting differences. 

```{r}
#Same code as above. 
models2 <- generateModels(k = 3)
models <- models2
models[c(10:13)] = models2[c(11:14)]
models[[14]] <- models2[[10]]

#Fixes issues with model 1 & 14. 
models[[1]] <- matrix(models[[1]], ncol = 3)
models[[14]] <- unname(models[[14]])

#Write MetascienceBa models
outputDir <- paste0(baseDir, "/FunctionsLoads/Loads/MetascienceBaLoads")
save(models, file = paste0(outputDir, "/models"))
```


```{r}

#Same code as above. 
models2 <- generateModels(k = 3)
models <- models2
models[c(10:13)] = models2[c(11:14)]
models[[14]] <- models2[[10]]

#Fixes issues with model 1 & 14. 
models[[1]] <- matrix(models[[1]], ncol = 3)
models[[14]] <- unname(models[[14]])

#Creating some models (formatting of model strings)
some_models <- NULL

for (N in 1:length(models)){
  some_models[N] <- modelToStr(models[[N]])
}

some_models <- str_replace(some_models, "Y ~", "")
some_models <- str_replace_all(some_models, ":", "")

#Write MetascienceBa models
outputDir <- paste0(baseDir, "/FunctionsLoads/Loads/MetascienceBaLoads")
save(some_models, file = paste0(outputDir, "/some_models"))

```

```{r}

setwd(paste0(baseDir, "/FunctionsLoads/Loads/MetascienceBaLoads"))
load("some_models")
some_models

setwd(paste0(baseDir, "/FunctionsLoads/Loads/MetascienceBaLoads"))
load("models")
models

```

