---
title: "Untitled"
author: "Victor Møller"
date: "November 27, 2019"
output: html_document
---

```{r setup, include=FALSE}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, rlist, nnet)
```

Paths 

```{r}
baseDir <- "."
scriptDir <- paste0(baseDir, "/src/functions")
inputDir <- paste0(baseDir, "/data")
outputDir <- paste0(baseDir, "/data")
```

Functions

```{r}

source(paste0(scriptDir, "/analysis.R"))
source(paste0(scriptDir, "/calculateDet.R"))
source(paste0(scriptDir, "/calculateDistance.R"))
source(paste0(scriptDir, "/compareModels.R"))
source(paste0(scriptDir, "/constants.R"))
source(paste0(scriptDir, "/convertBinary.R"))
source(paste0(scriptDir, "/generateBetas.R"))
source(paste0(scriptDir, "/generateModels.R"))
source(paste0(scriptDir, "/generateXSet.R"))
source(paste0(scriptDir, "/generateY.R"))
source(paste0(scriptDir, "/getBetas.R"))
source(paste0(scriptDir, "/getPredictors.R"))
source(paste0(scriptDir, "/modelSimilarByInteractionRework.R"))
source(paste0(scriptDir, "/modelSimilarByTermRework.R"))
source(paste0(scriptDir, "/modelToStr.R"))
source(paste0(scriptDir, "/searchModel.R"))
source(paste0(scriptDir, "/seedGenerator.R"))
source(paste0(scriptDir, "/simulator.R"))
source(paste0(scriptDir, "/strToModel.R"))

```

Technicalities (comment later)

```{r}
## Output filename
outputFile <- "output.csv"
paramFile <- "parameters.rds"

## Verbose mode
verbose <- TRUE

## Number of decimal places
ndec <- 4
```


Input parameters

```{r}
## Number of replications
replications <- 50

## Length of the simulation
timesteps <- 11000

## Number of factors
k <- 3

## Correlation
correlation <- 0.2

## Models (Fixed so that model 14 is not model 10). 
load(paste0(baseDir, "/connectivity/loads/models"))

## Identify the number of predictors of each model
predictors <- getPredictors(models)

## Generate Betas
weights <- generateBetas(models)

## modelselection 
modelSelection <- "hard"
```

ID variables to be looped over: 

```{r}

#Populations prep 
ReyCond <- list(nRey = 297, 
            nTess = 1, 
            nBo = 1, 
            nMave= 1)

TessCond <- list(nRey = 1, 
            nTess = 297, 
            nBo = 1, 
            nMave= 1)

BoCond <- list(nRey = 1, 
            nTess = 1, 
            nBo = 297, 
            nMave= 1)

MaveCond <- list(nRey = 1, 
            nTess = 1, 
            nBo = 1, 
            nMave= 297)

AllCond <- list(nRey = 1, 
            nTess = 1, 
            nBo = 1, 
            nMave= 1)

#ID variables we vary based on
populations <- list(ReyIndex = ReyCond, 
                    TessIndex = TessCond, 
                    BoIndex = BoCond, 
                    MaveIndex = MaveCond, 
                    AllIndex = AllCond)
sigmas <- list(0.2, 0.5, 0.8) #0.2, 0.5, 0.8 
sampleSizes <- list(100) #20, 100. 
tModels <- list(2, 7, 13) #2, 7, 13. 
modelCompares <- list(BIC, AIC) #AIC, BIC 


```

set seed 

```{r}
seeds <- seedGenerator(replications, paste0(inputDir, "/seeds.csv"))
```

Run the ABM 

```{r}

for (population in populations){
  for (sigma in sigmas){
    for (sampleSize in sampleSizes){
      for (tModel in tModels){
        for (modelCompare in modelCompares){
simulatorRework(populations, replications, timesteps, models, k, tModel,
  nRey, nTess, nBo, nMave, weights, sampleSize, correlation, sigma,
  modelCompare, modelSelection, inputDir, outputDir, outputFile, paramFile,
  verbose, ndec, seeds)
        }
      }
    }
  }
}

```

