---
title: "screening_BA"
author: "Victor Møller"
date: "17 sep 2019"
output: html_document
---

17-09-2019
Adapted from "true_false" Rmd to accomodate new data format. 
This document is designed to do qualitative tests / screening of data.
It is also designed to find interesting replicas so that RDS/networks
can be checked. 

```{r}

library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, ggunchained, tidyselect)

setwd("E:/data/dataPlotting")

```

Reading files 

```{r}

#read stuff & downsample 
Lattice <- read_csv("Lattice_true_false_CON_MetascienceBA.csv") %>%
  sample_frac(0.01) 

Small <- read_csv("Small_true_false_CON_MetascienceBA.csv") %>%
  sample_frac(0.01)

Combined <- rbind(Lattice, Small)

#clearing environment
rm("Lattice", "Small")

#factorize IDs 
factorize <- function(.df) {
  
  dataframe <- .df %>%
    mutate(population = factor(population),
         sigma = factor(sigma),
         true_model = factor(true_model),
         network = factor(network),
         net_size = factor(net_size),
         colab_cond = factor(colab_cond),
         replica = factor(replica),
         variable = factor(variable))  
  
  return(dataframe)
}

Combined <- factorize(Combined)

```

Plotting stuff 

```{r}


TAT_FUN <- function(.df, .sigma, .net, .tmod, .colab){
  
  sigma <- enquo(.sigma)
  net <- enquo(.net)
  tmod <- enquo(.tmod)
  colab <- enquo(.colab)

g <- .df %>%
  filter(sigma == UQ(sigma), 
         network == UQ(net), true_model == UQ(tmod), 
         colab_cond == UQ(colab)) %>%
  ggplot(aes(studies, value, color = true))+
  geom_point(alpha = 0.1) +
  geom_smooth(method = "loess", 
              se = F, 
              alpha = 0.1, 
              size = 1.2) +
  geom_hline(aes(yintercept = 0.5), 
             color = "red", 
             linetype = "dotted",
             size = 1,
             aes(labels = variable)) +
  #labs(x = "Studies", 
       #y = "Proportion", 
       #color = "Proportion of different models", 
       #title = "Proportion of agents at the true model",
       #subtitle = paste("Population:", population_p, "|", 
                        #"Sigma:", sigma_p, "|", 
                        #"True Model:", true_model_p)) +
  theme_janco_point() #+
  #facet_wrap(~network)

#call the plot
g

}

TAT_FUN(Combined, 0.2, "Lattice", 7, "NOLAB")

```


Plotting 
```{r}
#what you want to plot
sigma_p <- 0.5
population_p <- "Bo"
true_model_p <- 7
sample_size_p <- 100


g1 <- melt_new %>%
  filter(sigma == sigma_p, population == population_p, true_model == true_model_p, sample_size == sample_size_p) %>%
  ggplot(aes(studies, value, color = true))+
  geom_point(alpha = 0.1) +
  geom_smooth(method = "loess", se = F, alpha = 0.1, size = 1.2, aes(labels = variable)) +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dotted", size = 1) + 
  labs(x = "Studies", y = "Proportion", color = "Proportion of different models", 
       title = "Proportion of agents at the true model",
       subtitle = paste("Population:", population_p, "|", "Sigma:", sigma_p, "|", "True Model:", true_model_p)) +
  theme_janco_point() +
  facet_wrap(~network)

g1

```

Diagnostics

```{r}
Bo_subset <- df_new %>%
  filter(population == "Bo", sigma == 0.5, true_model == 7, network == "Lattice") %>%
  group_by(replica) %>%
  summarize(proportion = mean(proportion_true))

#replica 2 (very good), replica 3 (very bad). 

```

