---
title: "stickiness"
author: "Mikkel Werling"
date: "5/19/2019"
output: html_document
---


```{r}

setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_100")

#packages 
library(pacman)
p_load(tidyverse, ggunchained) 
```

loading data. 

```{r}
#reading 
path <- "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_20/"

files <- list.files(path = path, pattern="small") #if possible. 

mycols <- c("replica", 
            "network", 
            "population", 
            "sigma",
            "true_model",
            "initial_global_true_model",
            "final_global_true_model",
            "edges_already_true",
            "edges_already_true_changing")

#loading them 
dfList <- lapply(files, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
df <- do.call(rbind, dfList) 
rm(dfList)
```

computing stickiness.

```{r}

df1 <- df %>%
  group_by(replica, sigma, population, network, true_model) %>%
  summarize(agent_away = sum(as.numeric(initial_global_true_model == 1 & 
                                 final_global_true_model == 0)),
            agent_total = sum(as.numeric(initial_global_true_model == 1)),
            edge_away = sum(edges_already_true_changing),
            edge_total = sum(edges_already_true))

df2 <- df1 %>%
  mutate(all_losing_global = agent_away + edge_away,
         all_global_combined = agent_total + edge_total,
         stickiness = 1 - (all_losing_global / all_global_combined)) %>%
  group_by(network, population) %>%
  summarize(stickiness_median = median(stickiness),
            stickiness_mean = mean(stickiness),
            stickiness_IQR = IQR(stickiness), 
            stickiness_SD = sd(stickiness))

```

relevant subsets 

```{r}

#subsetting
stickiness_lattice <- df2 %>%
  filter(network == "Lattice") %>%
  select(population, network, stickiness_median, stickiness_mean, 
         stickiness_IQR, stickiness_SD)
  
stickiness_small <- df2 %>%
  filter(network == "Small") %>%
  select(population, network, stickiness_median, stickiness_mean, 
         stickiness_IQR, stickiness_SD)

#checking 
head(stickiness_lattice)
head(stickiness_small)

```

write csv

```{r}
#working directory
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/connectivity/outcome_results/sample_size_20")

getwd()
#writing csv
write.csv(stickiness_lattice, "stickiness_lattice_100.csv", row.names = F)
write.csv(stickiness_small, "stickiness_small_20.csv", row.names = F)

#checking
rm(list = ls())
stickiness_lattice <- read.csv("stickiness_lattice_100.csv")
stickiness_small <- read.csv("stickiness_small_100.csv")

#checking again
head(stickiness_lattice)
head(stickiness_small)

```

