---
title: "calculating"
author: "Mikkel Werling & Victor M?ller"
date: "5/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("E:/data/dataOutcomeMeasures")
library(tidyverse)

```

loading data

```{r}

TAT_C_AVG <- read_csv("TATC_AVG_MetascienceBA.csv")
TAT_C_REP <- read_csv("TATC_REP_MetascienceBA.csv")
  
```

For all variations of parameters: 

```{r}
#All parameters 
TAT_C_table <- TAT_C_REP %>%
  group_by(network, population, sigma, net_size, colab_cond, true_model) %>%
  summarise(TAT_C = round(mean(TAT_C),2)) 

```

Function which takes main effects: 

```{r}

TAT_FX <- function(.df, .grouping){
  
  grouping <- enquo(.grouping)
  
  df <- .df %>%
    group_by(UQ(grouping)) %>%
    summarize(TAT_median = round(median(TAT_C),2),
            TAT_mean = round(mean(TAT_C),2),
            TAT_IQR = round(IQR(TAT_C),2))
  return(df)
}

colnames(TAT_C_REP)

#replication consensus. 
TAT_FX(TAT_C_REP, network)
TAT_FX(TAT_C_REP, population)
TAT_FX(TAT_C_REP, sigma)
TAT_FX(TAT_C_REP, true_model)
TAT_FX(TAT_C_REP, net_size)
TAT_FX(TAT_C_REP, colab_cond)

```

Function which takes interactions: 

```{r}

TAT_FX2 <- function(.df, ...){
  
  group_var <- enquos(...)
  
  df <- .df %>%
    group_by(!!! group_var) %>%
    summarize(TAT_median = round(median(TAT_C),2),
            TAT_mean = round(mean(TAT_C),2),
            TAT_IQR = round(IQR(TAT_C),2))
  
  return(df)
}

#what can I group over?
colnames(TAT_C_REP)

#some tests (one could try more combinations)
TAT_NETPOP <- TAT_FX2(TAT_C_REP, network, population) #no interaction
TAT_SIGMOD <- TAT_FX2(TAT_C_REP, sigma, true_model) #interaction
TAT_SIGPOP <- TAT_FX2(TAT_C_REP, sigma, population) #not really. 
TAT_POPMOD <- TAT_FX2(TAT_C_REP, population, true_model)


```

Above chunk: 
waiting for more data from Mikkel to interpret. 

write csv. 

```{r}


```

