---
title: "TAT_TAT50"
author: "Victor Møller"
date: "26 maj 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("~/CRUST-1/data/tests")

library(tidyverse)

```

Loading & Early prep

```{r}
#reading stuff 
setwd("D:/data_outcome_measures")
TAT <- read_csv("TAT_TAT50.csv")
TAT_AVG <- read_csv("TAT_TAT50_AVG.csv")

#as factor
factorize <- function(dataframe){
  df <- dataframe %>%
    mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         base_SS = factor(base_SS),
         colab_cond = factor(colab_cond),
         net_size = factor(net_size),
         true_model = factor(true_model))
  
  return(df)
}

TAT <- factorize(TAT)
TAT_AVG <- factorize(TAT_AVG)
```



Subsets (main effects)

```{r}




#NETWORK & POP
TAT_network <- TAT %>%
  group_by(network) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = mean(TAT50),
            TAT50_IQR = IQR(TAT50))

#SIGMA
TAT_sigma <- TAT %>%
  group_by(sigma) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = round(mean(TAT50),2),
            TAT50_IQR = IQR(TAT50))

#MODEL
TAT_true <- TAT %>%
  group_by(true_model) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT50_median = median(TAT50),
            TAT50_mean = round(mean(TAT50),2),
            TAT50_IQR = IQR(TAT50))


```


write csv 

```{r}
#new working directory 
setwd("~/CRUST-1/connectivity/outcome_results")
      
#write csv
write.csv(TAT_lattice_100, "TAT_lattice_100.csv", row.names = FALSE)
write.csv(TAT_small_100, "TAT_small_100.csv", row.names = FALSE)
write.csv(TAT50_lattice_100, "TAT50_lattice_100.csv", row.names = FALSE)
write.csv(TAT50_small_100, "TAT50_small_100.csv", row.names = FALSE)

```

