---
title: "colab"
author: "Victor Møller"
date: "November 23, 2019"
output: html_document
---

```{r setup, include=FALSE}

#set working directory
setwd("E:/data_prepped1")

#packages 
library(pacman)
p_load(tidyverse, ggunchained) 

```



```{r}

test <- read_csv("Lattice_All_0.2_BIC_413_hard_20_2-COLAB.csv")

summary(test$SS)

#subsets 
colab <- test %>%
  filter(strategy == "colab") 

research <- test %>%
  filter(strategy == "research")

neighbor <- test %>%
  filter(strategy == "neighbor")

#prop true 
c_prop <- colab %>%
  group_by(prop_t_mod) %>%
  summarise(count = n())

r_prop <- research %>%
  group_by(prop_t_mod) %>%
  summarise(count = n())

n_prop <- neighbor %>%
  group_by(prop_t_mod) %>%
  summarise(count = n())

#effect (prep)
c_effect <- colab %>%
  filter(prop_t_mod == 1) %>%
  mutate(effect = (final_g_true - init_g_true) + switch_changing)

r_effect <- research %>%
  filter(prop_t_mod == 1) %>%
  mutate(effect = (final_g_true - init_g_true) + switch_changing)

n_effect <- neighbor %>%
  filter(prop_t_mod == 1) %>%
  mutate(effect = (final_g_true - init_g_true) + switch_changing)

#effect (measured)


```

