---
title: "bayesian_sensation"
author: "Victor Møller"
date: "6 maj 2019"
output: html_document
---

```{r setup, include=FALSE}

library(pacman)
p_load(tidyverse, readxl, brms, metafor, brmstools, ggunchained, cowplot, ggthemes)

```

simulating values:

time to true (50%) ~ population * network 
taken from p. 13

```{r}

#come back to this. 
#listxx <- list(m_all, m_all_sw, m_bo)
#x <- lapply(listxx, data.frame)

#per population lattice (hypothetical, taken from paper)
tess <- abs(rnorm(1000, mean = 3.79, sd = 1.63))
mave <- abs(rnorm(1000, mean = 4.51, sd = 1.58))
bo <- abs(rnorm(1000, mean = 6.43, sd = 3.00))
all <- abs(rnorm(1000, mean = 4.19, sd = 1.65))

#per population small world (hypothetical, better than paper)
tess_sw <- abs(rnorm(1000, mean = 3.11, sd = 1.5))
mave_sw <- abs(rnorm(1000, mean = 4.2, sd = 1.4))
bo_sw <- abs(rnorm(1000, mean = 5.21, sd = 2.53))
all_sw <- abs(rnorm(1000, mean = 3.82, sd = 1.34))

#tess ttt
tess <- data.frame(tess)
tess <- tess %>%
  mutate(agent = "Tess",
         network = "lattice") %>%
  rename(time_to_true = "tess")

tess_sw <- data.frame(tess_sw)
tess_sw <- tess_sw %>%
  mutate(agent = "Tess",
         network = "small") %>%
  rename(time_to_true = "tess_sw")

#mave 
mave <- data.frame(mave)
mave <- mave %>%
  mutate(agent = "Mave",
         network = "lattice") %>%
  rename(time_to_true = "mave")

mave_sw <- data.frame(mave_sw)
mave_sw <- mave_sw %>%
  mutate(agent = "Mave",
         network = "small") %>%
  rename(time_to_true = "mave_sw")

#bo 
bo <- data.frame(bo)
bo <- bo %>%
  mutate(agent = "Bo",
         network = "lattice") %>%
  rename(time_to_true = "bo")

bo_sw <- data.frame(bo_sw)
bo_sw <- bo_sw %>%
  mutate(agent = "Bo",
         network = "small") %>%
  rename(time_to_true = "bo_sw")

#all 
all <- data.frame(all)
all <- all %>%
  mutate(agent = "All",
         network = "lattice") %>%
  rename(time_to_true = "all")

all_sw <- data.frame(all_sw)
all_sw <- all_sw %>%
  mutate(agent = "All",
         network = "small") %>%
  rename(time_to_true = "all_sw")


```

stickiness (between 0-1).
p. 39

```{r}

#per population lattice
s_tess <- rnorm(1000, mean = 0.75, sd = 0.2)
s_mave <- rnorm(1000, mean = 0.7, sd = 0.15)
s_bo <- rnorm(1000, mean = 0.8, sd = 0.15)
s_all <- rnorm(1000, mean = 0.85, sd = 0.15)

#per population small world
s_tess_sw <- rnorm(1000, mean = 0.85, sd = 0.14)
s_mave_sw <- rnorm(1000, mean = 0.9, sd = 0.18)
s_bo_sw <- rnorm(1000, mean = 0.9, sd = 0.22)
s_all_sw <- rnorm(1000, mean = 0.91, sd = 0.21)

#tess stickiness
s_tess <- data.frame(s_tess)
s_tess <- s_tess %>%
  mutate(agent = "Tess",
         network = "lattice") %>%
  rename(stickiness = "s_tess")

s_tess_sw <- data.frame(s_tess_sw)
s_tess_sw <- s_tess_sw %>%
  mutate(agent = "Tess",
         network = "small") %>%
  rename(stickiness = "s_tess_sw")

#mave stickiness
s_mave <- data.frame(s_mave)
s_mave <- s_mave %>%
  mutate(agent = "Mave",
         network = "lattice") %>%
  rename(stickiness = "s_mave")

s_mave_sw <- data.frame(s_mave_sw)
s_mave_sw <- s_mave_sw %>%
  mutate(agent = "Mave",
         network = "small") %>%
  rename(stickiness = "s_mave_sw")

#bo
s_bo <- data.frame(s_bo)
s_bo <- s_bo %>%
  mutate(agent = "Bo",
         network = "lattice") %>%
  rename(stickiness = "s_bo")

s_bo_sw <- data.frame(s_bo_sw)
s_bo_sw <- s_bo_sw %>%
  mutate(agent = "Bo",
         network = "small") %>%
  rename(stickiness = "s_bo_sw")

#all
s_all <- data.frame(s_all)
s_all <- s_all %>%
  mutate(agent = "All",
         network = "lattice") %>%
  rename(stickiness = "s_all")

s_all_sw <- data.frame(s_all_sw)
s_all_sw <- s_all_sw %>%
  mutate(agent = "All",
         network = "small") %>%
  rename(stickiness = "s_all_sw")

```

mean time at true model.
as a percentage (0-1)
p. 28

```{r}

set.seed(711)
#lattice
m_tess <- rnorm(1000, mean = 0.34, sd = 0.1)
m_mave <- rnorm(1000, mean = 0.51, sd = 0.1)
m_bo <- rnorm(1000, mean = 0.34, sd = 0.1)
m_all <- rnorm(1000, mean = 0.65, sd = 0.1)

#small world
m_tess_sw <- rnorm(1000, mean = 0.53, sd = 0.1)
m_mave_sw <- rnorm(1000, mean = 0.44, sd = 0.1)
m_bo_sw <- rnorm(1000, mean = 0.66, sd = 0.1)
m_all_sw <- rnorm(1000, mean = 0.71, sd = 0.1)

#tess mean time
m_tess <- data.frame(m_tess)
m_tess <- m_tess %>%
  mutate(agent = "Tess",
         network = "lattice") %>%
  rename(meantime = "m_tess")

m_tess_sw <- data.frame(m_tess_sw)
m_tess_sw <- m_tess_sw %>%
  mutate(agent = "Tess",
         network = "small") %>%
  rename(meantime = "m_tess_sw")

#mave mean time 
m_mave <- data.frame(m_mave)
m_mave <- m_mave %>%
  mutate(agent = "Mave",
         network = "lattice") %>%
  rename(meantime = "m_mave")

m_mave_sw <- data.frame(m_mave_sw)
m_mave_sw <- m_mave_sw %>%
  mutate(agent = "Mave",
         network = "small") %>%
  rename(meantime = "m_mave_sw")

#bo mean time 
m_bo <- data.frame(m_bo)
m_bo <- m_bo %>%
  mutate(agent = "Bo",
         network = "lattice") %>%
  rename(meantime = "m_bo")

m_bo_sw <- data.frame(m_bo_sw)
m_bo_sw <- m_bo_sw %>%
  mutate(agent = "Bo",
         network = "small") %>%
  rename(meantime = "m_bo_sw")

#all mean time
m_all <- data.frame(m_all)
m_all <- m_all %>%
  mutate(agent = "All",
         network = "lattice") %>%
  rename(meantime = "m_all")

m_all_sw <- data.frame(m_all_sw)
m_all_sw <- m_all_sw %>%
  mutate(agent = "All",
         network = "small") %>%
  rename(meantime = "m_all_sw")


```

formatting everything

```{r}
#time to true lattice
time_lat <- rbind(all, bo, mave, tess)
rm(all, bo, mave, tess)

#time to true small
time_small <- rbind(all_sw, bo_sw, mave_sw, tess_sw)
rm(all_sw, bo_sw, mave_sw, tess_sw)

#sticky lattice
stick_lat <- rbind(s_all, s_bo, s_mave, s_tess)
rm(s_all, s_bo, s_mave, s_tess)

#sticky small
stick_small <- rbind(s_all_sw, s_bo_sw, s_mave_sw, s_tess_sw)
rm(s_all_sw, s_bo_sw, s_mave_sw, s_tess_sw)

#mean time lattice
mean_stick <- rbind(m_all, m_bo, m_mave, m_tess) #should have been mean lat
rm(m_all, m_bo, m_mave, m_tess)

#mean time small world 
mean_small <- rbind(m_all_sw, m_bo_sw, m_mave_sw, m_tess_sw)
rm(m_all_sw, m_bo_sw, m_mave_sw, m_tess_sw)

```

putting more together 

```{r}
timeto <- rbind(time_lat, time_small)
meantime <- rbind(mean_small, mean_stick)
stickiness <- rbind(stick_lat, stick_small)

rm(time_lat, time_small, mean_small, mean_stick, stick_lat, stick_small)

#as factor
meantime$agent <- as.factor(meantime$agent)
meantime$network <- as.factor(meantime$network)
stickiness$agent <- as.factor(stickiness$agent)
stickiness$network <- as.factor(stickiness$network)
timeto$network <- as.factor(timeto$network)
timeto$agent <- as.factor(timeto$agent)

#saving
write.csv(timeto,file="bayes/timeto.csv", row.names = FALSE)
write.csv(meantime, file= "bayes/meantime.csv", row.names = FALSE)
write.csv(stickiness, file = "bayes/stickiness.csv", row.names = FALSE)

```

crazy stuff (probably not relevant): 
expanded with levels & simplified levels

```{r}

#generating numbers from 1:12
complexity <- rep(1:12, 667)

#deleting a couple
complexity <- complexity[-1:-4]

#putting into the model
meantime$complex <- complexity
meantime$complex <- as.factor(meantime$complex)

#simplified 
meantime <- meantime %>%
  mutate(sim_com = rep(1:2, 4000)) 

meantime$sim_com <- as.factor(meantime$sim_com)

```

model with expansion.
nothing will ever be significant (& also I don't think this is what we want). 

```{r}

#model call
mod_f <- bf("meantime ~ agent * network * sim_com")
get_prior(mod_f, meantime, family = gaussian())

#running the model with regularizing priors 
mod_mod <- brm(
  mod_f, 
  prior = c(
    prior(normal(0, 2), class = "Intercept"),
    prior(normal(0, 2), class = "b"),
    prior(normal(0, 2), class = "sigma")),
  data = meantime, 
  cores = 4, iter = 4000, warmup = 2000,
  sample_prior = TRUE, #added for later use. 
  file = "bayes/mod_mod" #saving for later use - these models take ages to run. 
)

mod_mod
```

