---
title: "TAT_TAT50"
author: "Victor Møller"
date: "26 maj 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("D:/data/data_outcome_measures")
library(tidyverse)

```

Loading & Early prep

```{r}

#reading stuff
TAT_Devezer <- read_csv("TAT_TAT50_Devezer_original.csv")
TAT_MOD <- read_csv("TAT_TAT50_Devezer_fixed.csv")

#as factor
factorize <- function(dataframe){
  df <- dataframe %>%
    mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         true_model = factor(true_model),
         base_SS = factor(base_SS),
         modelcompare = factor(modelcompare))
  
  return(df)
}

TAT_Devezer <- factorize(TAT_Devezer)
TAT_MOD <- factorize(TAT_MOD)

TAT_100_both <- TAT_MOD %>%
  filter(base_SS == 100)

TAT_20_both <- TAT_MOD %>%
  filter(base_SS == 20)

TAT_20_BIC <- TAT_MOD %>%
  filter(base_SS == 20, modelcompare == "BIC")

```

Main effects: 

```{r}

#Function approach
TAT_FX <- function(.df, .grouping){

  grouping <- enquo(.grouping)
  
  df <- .df %>%
  group_by(UQ(grouping)) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT_SD = sd(TAT))
  
  return(df)
  
}

#TATS
TAT_Devezer_table <- TAT_FX(TAT_Devezer, population) #what we write. 
TAT_100_both_table <- TAT_FX(TAT_100_both, population)
TAT_20_both_table <- TAT_FX(TAT_20_both, population)
TAT_20_BIC_table <- TAT_FX(TAT_20_BIC, population)
```

write csv 

```{r}

setwd("~/CRUST-1/DevezerAlteredAgents/data/outcome_tables")
write_csv(TAT_Devezer_table, "TAT_Devezer.csv")
write_csv(TAT_100_both_table, "TAT_100_both.csv")
write_csv(TAT_20_both_table, "TAT_20_both.csv")
write_csv(TAT_20_BIC_table, "TAT_20_BIC.csv")

```

