---
title: "true_false_only"
author: "Mikkel Werling"
date: "11/25/2019"
output: html_document
---


```{r}
library(pacman)

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, ggunchained, tidyselect)
```


READ DATA

```{r}
setwd("D:/data/data_plotting")
df <- read_csv("true_false_rework_only_true.csv")
```

OVERVIEW OF THE DATA

```{r}

overview <- df %>%
  group_by(sigma, true_model, network, population) %>%
  summarize(count = max(replica))
```

PLOTTING

```{r}

network_p <- "Small"
true_model_p <- 13
sigma_p <- 0.8

g1 <- df %>%
  filter(sigma == sigma_p, true_model == true_model_p, network == network_p) %>%
  ggplot(aes(studies, value, color = population))+
  geom_point(alpha = 0.1) +
  geom_smooth(method = "loess", se = F, alpha = 0.1, size = 1.2, aes(labels = variable)) +
  geom_hline(aes(yintercept = 0.5), color = "red", linetype = "dotted", size = 1) + 
  labs(x = "Studies", y = "Proportion", color = "Proportion of different models", 
       title = "Proportion of agents at the true model",
       subtitle = paste("Network:", network_p, "|", "All Populations", "|", "Sigma:", sigma_p, "|", "True Model:", true_model_p)) +
  theme_janco_point()

g1


```

