---
title: "Untitled"
author: "Victor Møller"
date: "20 maj 2019"
output: html_document
---

packages & working directory. 

```{r}
library(pacman)
p_load(readr, tidyverse, ggplot2, RColorBrewer, reshape2, ggthemes)

```

loading data. 

```{r}
#working directory. 
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_100")

path = "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_100/"

files_100 <- list.files(path = path, pattern="*small")

#taken from the scatter-plot file (reconsider what is needed)
mycols <- c("replica", 
            "turn", 
            "studies", 
            "network", 
            "population", 
            "sigma",
            "sample_size",
            "true_model",
            "strategy",
            "edges_replication_study",
            "edges_replicated",
            "proportion_true",
            "final_global_true_model")

#loading them 
dfList <- lapply(files_100, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
small_100 <- do.call(rbind, dfList) 
rm(dfList)
```

loading data. 

```{r}
#working directory. 
setwd("C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_20")

path = "C:/Users/victm/Dropbox/CogSci 4/Social and Cultural Dynamics in Cognition/exam/CRUST-1/data/ABMdata/ABMcsv/sample_size_20/"

files_20 <- list.files(path = path, pattern="*small")

getwd()
#taken from the scatter-plot file (reconsider what is needed)
mycols <- c("replica", 
            "turn", 
            "studies", 
            "network", 
            "population", 
            "sigma",
            "sample_size",
            "true_model",
            "strategy",
            "edges_replication_study",
            "edges_replicated",
            "proportion_true",
            "final_global_true_model")

#loading them 
dfList <- lapply(files_20, function(f) {  
   read.csv(paste0(path, f))[mycols]
})

#subsetting (because of computational demands)
small_20 <- do.call(rbind, dfList) 
rm(dfList)
```

Preprocessing (should also be adjusted to accommodate better early prep). 

```{r}

#rbinding 
small <- rbind(small_100, small_20)

#factorizing
small$network <- as.factor(small$network)
small$true_model <- as.factor(small$true_model)
small$sample_size <- as.factor(small$sample_size)

```


with RR for true model (preprocessing)
by global

```{r}

#replication rate small world 
small_RR_TAT <- small %>%
  group_by(replica, sample_size, network, population, sigma, true_model) %>%
  summarize(RR = sum(edges_replicated) / sum(edges_replication_study),
            TAT = mean(proportion_true)) %>%
  ungroup %>%
  mutate(sample_size = ifelse(sample_size == 20, 
                              "Sample size: 20",
                              "Sample size: 100"))

#creating the grouped by (3 rows missing)
by_global <- small %>%
  group_by(final_global_true_model, replica, network, population, 
           true_model, sigma, sample_size) %>%
  summarize(RR = sum(edges_replicated) / sum(edges_replication_study),
            TAT = mean(proportion_true)) %>%
  filter(final_global_true_model == 1) %>%
  ungroup %>%
  mutate(sample_size = ifelse(sample_size == 20,
                              "Sample size: 20",
                              "Sample size: 100"))

#adding stuff.  
small_RR <- small_RR_TAT %>%
  mutate(final_global_true_model = "Overall") 

#changing stuff
by_global$final_global_true_model <- "True"

#cbinding 
all_overall <- rbind(by_global, small_RR)

#factor. 
all_overall$final_global_true_model <- as.factor(all_overall$final_global_true_model)

#changing names 
all_overall <- all_overall %>%
  rename("Population" = "population", 
         "Network" = "network",
         "Sigma" = "sigma")

#melting
small_melt <- melt(all_overall, id.vars = c("replica", "Population", "Sigma", "true_model", "sample_size", "final_global_true_model"), measure.vars = c("RR", "TAT"), variable.name = "variable", value.name = "proportion")
```

ridges plot.
Replication rate vs. time at true model. 
remember to change sample size to obtain different outputs. 

```{r}

#packages
p_load(viridis, ggridges)

#ridges plot
g <- small_melt %>%
  filter(final_global_true_model == "Overall",
         sample_size == "Sample size: 20") %>%
  ggplot(aes(x = proportion, y = Population, 
                           color = variable, fill = variable)) +
  geom_density_ridges(jittered_points = TRUE, scale = 0.8, rel_min_height = .01,
                      point_shape = "|", point_size = 3, size = 0.25, 
                      position = position_points_jitter(height = 0)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  scale_x_continuous(expand = c(0,0), 
                     name = "Replication rate & time at true model") +
  scale_fill_manual(values = c("#D55E0050", "#0072B250"), 
                    labels = c("Replication rate", "Time at true model")) +
  scale_color_manual(values = c("#D55E00", "#0072B2"), guide = "none") +
  scale_discrete_manual("point_color", values = c("#D55E00", "#0072B2"), 
                        guide = "none") +
  guides(fill = guide_legend("",
    override.aes = list(
    fill = c("#D55E00A0", "#0072B2A0"),
    color = NA, point_color = NA))
  ) +
  theme_ridges(center = TRUE) + 
  theme_janco_point() 
  
g + labs(caption = "Sample size: 100. 'Replication rate' and 'proportion of time at the true model' both on the x-axis. \n Density curves are averaged over sigma-levels, true models and replicas. \n Lines at the bottom represent mean values for individual replicas") +
  theme(plot.caption = element_text(hjust = 0.5))

library(ggunchained)
```

ridges plot. 
true vs. overall.
remember to change sample size to vary. 

```{r}

#melting again
small_RR_melt <- melt(all_overall, id.vars = c("replica", "Population", "Sigma", "true_model", "sample_size", "final_global_true_model"), measure.vars = c("RR"), variable.name = "variable", value.name = "proportion")

#packages
p_load(viridis, ggridges)

#ridges plot
g1 <- small_RR_melt %>%
  filter(sample_size == "Sample size: 20") %>%
  ggplot(aes(x = proportion, y = Population,
             color = final_global_true_model, 
             fill = final_global_true_model)) +
  geom_density_ridges(jittered_points = TRUE, scale = 0.8, rel_min_height = .01,
                      point_shape = "|", point_size = 3, size = 0.25, 
                      position = position_points_jitter(height = 0)) +
  scale_y_discrete(expand = c(0.01, 0)) +
  xlim(0,1) + xlab("Replication rate") +
  scale_fill_manual(values = c("#D55E0050", "#0072B250")) +
  scale_color_manual(values = c("#D55E00", "#0072B2"), guide = "none") +
  scale_discrete_manual("point_color", values = c("#D55E00", "#0072B2"), 
                        guide = "none") +
  guides(fill = guide_legend("",
    override.aes = list(
    fill = c("#D55E00A0", "#0072B2A0"),
    color = NA, point_color = NA))) + 
  theme_ridges(center = TRUE) +
    theme_janco_point() 
  
g1 + labs(caption = "Sample size: 20. Density curves are averaged over sigma-levels, true models and replicas. \n Lines at the bottom represent mean values for individual replicas") +
  theme(plot.caption = element_text(hjust = 0.5))


```

