---
title: "citation_network"
author: "Mikkel Werling"
date: "9/5/2019"
output: html_document
---

CURRENT NETWORK:
Vertices: 232
Max Degree: 84
Mean Degree: 5.81
____________________
CURRENT NETWORK (without filter)
Vertices: 1027
Max Degree: 686
Mean Degree: 26.47
Median Degree: 17

```{r}
library(pacman)
p_load(bibliometrix)
p_load(igraph)
p_load(ggraph)
p_load(tidyverse)
p_load(stringr)
```

Reading the data file

```{r}
setwd("~/CRUST-1/citation_network/Theory Of Mind")

temp <- list.files(pattern="*bib")

D <- readFiles(temp[1], temp[2], temp[3], temp[4])

M <- convert2df(D, dbsource = "isi", format = "bibtex")

```

parsing CR.

```{r}
#limiting publications by year (note: explodes into 1027 without limiting)

#M <- M %>%
 #filter(PY >= 2017)

cited <- str_split(M$CR, ";") #cited ref. are split by semicolon in CR column. 

first_cited <- lapply(cited, str_extract, "[^,]+") #extract all the first authors 
#this is a big decision, come back - ask someone, etc. 

data <- data.frame()

#evt. change hard-cording & first_cited[[1]] without [[1]] in colname. 
for (i in 1:nrow(M)){ #hardcoded for the number of in the list of "first_cited" 
  assign("new_mode", as.data.frame(first_cited[[i]])) #first in references. 
  new_mode$original <- M$AU[i] #original = author. 
  data <- rbind(new_mode,data)
}

#making sure that we only get first author of the paper (not reference).
data$original <- lapply(data$original, str_extract, "[^;]+")

#shifting columns. 
data <- data %>%
  select(original, `first_cited[[i]]`)

```

Parsing the authors and the references

```{r}

cleaned_data <- data
cleaned_data <- na.omit(cleaned_data) #get rid of NA. 
cleaned_data$`first_cited[[i]]` <- as.character(cleaned_data$`first_cited[[i]]`) #as character instead of factor

#get rid of digits
cleaned_data$number_detection <- str_detect(cleaned_data$`first_cited[[i]]`, "[:digit:]") 

#stars in the names seemed to be a nuisance
cleaned_data$star_detection <- str_detect(cleaned_data$`first_cited[[i]]`, "\\*") 

#anonymous flagged. 
cleaned_data$anon_detection <- str_detect(cleaned_data$`first_cited[[i]]`, "ANONYMOUS") #don't want any anonymous in the data

#if some were listed as NA. 
cleaned_data$na_detection <- cleaned_data$`first_cited[[i]]`=="NA" 

#all the data without issues. 
data_new <- cleaned_data %>%
  filter(star_detection == F, number_detection == F, 
         anon_detection == F, na_detection == F)

#In order to make direct comparisons between authors and references, we have to make them exactly the same

#removing all the punctuation and replacing it with blank space
data_new$`first_cited[[i]]` <- str_replace_all(data_new$`first_cited[[i]]`, "[:punct:]", "") 
data_new$original <- str_replace_all(data_new$original, "[:punct:]", "") 

#removing blank space from references & authors. 
data_new$`first_cited[[i]]` <- str_replace_all(data_new$`first_cited[[i]]`, "[:space:]", "") 
data_new$original <- str_replace_all(data_new$original, "[:space:]", "") 

#still issues.. 

#noting when authors quote themselves
data_new$match <- data_new$original == data_new$`first_cited[[i]]` 

##check if the author is also ref. (deletes a lot of data). 
data_new$ref <- data_new$original %in% data_new$`first_cited[[i]]` & data_new$`first_cited[[i]]` %in% data_new$original

while(all(data_new$ref)!=T){
 data_new <- data_new %>%
  filter(ref == T)
data_new$ref <- data_new$original %in% data_new$`first_cited[[i]]` & data_new$`first_cited[[i]]` %in% data_new$original
}

#de-selecting dummy-variables. 
data_new <- data_new %>%
  select(original, `first_cited[[i]]`)

#removing duplicates (this would be relevant for weighted).
data_new_1 <- distinct(data_new) 


```

Network visualization. 

```{r}

g <- graph_from_data_frame(data_new_1, directed = F)

#remove multiple edges and loops. Should already be gone from cleaning though. 
g <- igraph::simplify(g) 

#main component (biggest connected network), exclude rest.
g <- induced_subgraph(
  g, V(g)[components(g)$membership == which.max(components(g)$csize)]
) 

#how many vertices
length(V(g))

#max degree
max(degree(g))

#average degree
mean(degree(g))

#median degree
median(degree(g))

which(degree(g)==max(degree(g)))

sort(degree(g), decreasing = T)



#plotting
ggraph(g, "kk")+
  geom_node_point(aes(size = degree(g), alpha = degree(g)))+
  geom_edge_fan(alpha = 0.2)+
  theme_graph()

#as circle 
ggraph(g, "circle")+
  geom_node_point(aes(size = degree(g), alpha = degree(g)))+
  geom_edge_fan(alpha = 0.2)+
  theme_graph()

#save the file
saveRDS(g, "~/CRUST-1/citation_network/g.rds")

readRDS("~/CRUST-1/citation_network/g.rds")
```

Diagnostics.
Check up on these generally. 

```{r}
average.path.length(g) #getting the average path length 
transitivity(g) #clustering coefficient 
closeness(g) #unsure what this really means - what kind of closeness measure is this?
assortativity_degree(g, directed = F) 

#distribution of the degrees
deg.dist <- degree_distribution(g, cumulative=T, mode="all")
plot( x=0:max(degree(g)), y=1-deg.dist, pch=19, cex=1.2, col="orange", 
      xlab="Degree", ylab="Cumulative Frequency")
```

