---
title: "stickiness"
author: "Mikkel Werling"
date: "5/19/2019"
output: html_document
---

Updated 6-12-2019

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working directory
setwd("~/CRUST-1/MetascienceBA/data/outcome_measures")

#packages 
library(pacman)
p_load(tidyverse, ggunchained, rlang) 
```

loading data. 

```{r}

stickiness <- read_csv("stickiness_MetascienceBA.csv")

#as factor
factorize <- function(dataframe){
  df <- dataframe %>%
    mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         colab_cond = factor(colab_cond),
         net_size = factor(net_size),
         true_model = factor(true_model),
         stickiness = stickiness_overall) 
  
  return(df)
}

stickiness <- factorize(stickiness)

```

Subsets

```{r}

#those where we group over three IDs. 
group3 <- function(.df, .net, .size, .colab){
  
  net <- enquo(.net)
  size <- enquo(.size)
  colab <- enquo(.colab)
  
  dataframe <- .df %>%
    filter(network == UQ(net),
           net_size == UQ(size),
           colab_cond == UQ(colab))
 
  return(dataframe) 
}

stickiness_LATTICE_413_NOLAB <- group3(stickiness, "Lattice", 413, "NOLAB")
stickiness_SMALL_413_NOLAB <- group3(stickiness, "Small", 413, "NOLAB")
stickiness_LATTICE_484_NOLAB <- group3(stickiness, "Lattice", 484, "NOLAB")
stickiness_SMALL_484_NOLAB <- group3(stickiness, "Small", 484, "NOLAB")

#those where we group over two IDs. 
group2 <- function(.df, .net, .colab){
  
  net <- enquo(.net)
  colab <- enquo(.colab)
  
  dataframe <- .df %>%
    filter(network == UQ(net),
           colab_cond == UQ(colab))
 
  return(dataframe) 
}

stickiness_LATTICE_NOLAB <- group2(stickiness, "Lattice", "NOLAB")
stickiness_SMALL_NOLAB <- group2(stickiness, "Small", "NOLAB")
stickiness_LATTICE_COLAB <- group2(stickiness, "Lattice", "COLAB")
stickiness_SMALL_COLAB <- group2(stickiness, "Small", "COLAB")
stickiness_TOM_COLAB <- group2(stickiness, "TOM", "COLAB")
stickiness_PT_COLAB <- group2(stickiness, "PT", "COLAB")

#those where we group over one ID.  
group1 <- function(.df, .net1, .net2){
  
  net1 <- enquo(.net1)
  net2 <- enquo(.net2)
  
  dataframe <- .df %>%
    filter(network == UQ(net1) | network == UQ(net2))
 
  return(dataframe) 
}

stickiness_CITATION_COLAB <- group1(stickiness, "TOM", "PT")

```

```{r}
stickiness_FUN <- function(.dataframe, .var1){
  
  var1 <- enquo(.var1)
  
  df <- .dataframe %>%
  group_by(UQ(var1)) %>%
  summarize(stickiness_mean = mean(stickiness),
            stickiness_median = median(stickiness),
            stickiness_IQR = IQR(stickiness),
            stickiness_SD = sd(stickiness))
  
  return(df)
  
}

#Do it for all 11 dataframes. 
stickiness_LATTICE_413_NOLAB <- stickiness_FUN(stickiness_LATTICE_413_NOLAB, population)
stickiness_SMALL_413_NOLAB <- stickiness_FUN(stickiness_SMALL_413_NOLAB, population)
stickiness_LATTICE_484_NOLAB <- stickiness_FUN(stickiness_LATTICE_484_NOLAB, population)
stickiness_SMALL_484_NOLAB <- stickiness_FUN(stickiness_SMALL_484_NOLAB, population)
stickiness_LATTICE_NOLAB <- stickiness_FUN(stickiness_LATTICE_NOLAB, population)
stickiness_SMALL_NOLAB <- stickiness_FUN(stickiness_SMALL_NOLAB, population)
stickiness_LATTICE_COLAB <- stickiness_FUN(stickiness_LATTICE_COLAB, population)
stickiness_SMALL_COLAB <- stickiness_FUN(stickiness_SMALL_COLAB, population)
stickiness_TOM_COLAB <- stickiness_FUN(stickiness_TOM_COLAB, population)
stickiness_PT_COLAB <- stickiness_FUN(stickiness_PT_COLAB, population)
stickiness_CITATION_COLAB <- stickiness_FUN(stickiness_CITATION_COLAB, population)

rm(stickiness, stickiness_FUN, group1, group2, group3)
```

write csv 

```{r}

setwd("~/CRUST-1/MetascienceBA/data/outcome_tables")

writeFUN <- function(df){
  
  df_name <- deparse(substitute(df))
  write_csv(df, paste0(df_name, ".csv"))
  
}

writeFUN(stickiness_LATTICE_413_NOLAB)
writeFUN(stickiness_SMALL_413_NOLAB)
writeFUN(stickiness_LATTICE_484_NOLAB)
writeFUN(stickiness_SMALL_484_NOLAB)
writeFUN(stickiness_LATTICE_NOLAB)
writeFUN(stickiness_SMALL_NOLAB)
writeFUN(stickiness_LATTICE_COLAB)
writeFUN(stickiness_SMALL_COLAB)
writeFUN(stickiness_TOM_COLAB)
writeFUN(stickiness_PT_COLAB)
writeFUN(stickiness_CITATION_COLAB)

```


