---
title: "over 100 sketch"
author: "Mikkel Werling"
date: "5/26/2019"
output: html_document
---

Updated 6-12-2019

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#set working directory
setwd("~/CRUST-1/MetascienceBA/data/outcome_measures")

#packages 
library(pacman)
p_load(tidyverse, ggunchained, rlang) 
```

loading data & early prep. 

```{r}

#read data 
FPTT <- read_csv("FPTT_MetascienceBA.csv")

#as factor, no NA/Inf & selecting relevant columns. 
FPTT <- na.omit(FPTT)

FPTT <- FPTT %>%
  mutate(network = factor(network),
        population = factor(population),
        sigma = factor(sigma),
        colab_cond = factor(colab_cond),
        net_size = factor(net_size),
        true_model = factor(true_model))


```

subsets. 

```{r}

#those where we group over three IDs. 
group3 <- function(.df, .net, .size, .colab){
  
  net <- enquo(.net)
  size <- enquo(.size)
  colab <- enquo(.colab)
  
  dataframe <- .df %>%
    filter(network == UQ(net),
           net_size == UQ(size),
           colab_cond == UQ(colab))
 
  return(dataframe) 
}

FPTT_LATTICE_413_NOLAB <- group3(FPTT, "Lattice", 413, "NOLAB")
FPTT_SMALL_413_NOLAB <- group3(FPTT, "Small", 413, "NOLAB")
FPTT_LATTICE_484_NOLAB <- group3(FPTT, "Lattice", 484, "NOLAB")
FPTT_SMALL_484_NOLAB <- group3(FPTT, "Small", 484, "NOLAB")

#those where we group over two IDs. 
group2 <- function(.df, .net, .colab){
  
  net <- enquo(.net)
  colab <- enquo(.colab)
  
  dataframe <- .df %>%
    filter(network == UQ(net),
           colab_cond == UQ(colab))
 
  return(dataframe) 
}

FPTT_LATTICE_NOLAB <- group2(FPTT, "Lattice", "NOLAB")
FPTT_SMALL_NOLAB <- group2(FPTT, "Small", "NOLAB")
FPTT_LATTICE_COLAB <- group2(FPTT, "Lattice", "COLAB")
FPTT_SMALL_COLAB <- group2(FPTT, "Small", "COLAB")
FPTT_TOM_COLAB <- group2(FPTT, "TOM", "COLAB")
FPTT_PT_COLAB <- group2(FPTT, "PT", "COLAB")

#those where we group over one ID.  
group1 <- function(.df, .net1, .net2){
  
  net1 <- enquo(.net1)
  net2 <- enquo(.net2)
  
  dataframe <- .df %>%
    filter(network == UQ(net1) | network == UQ(net2))
 
  return(dataframe) 
}

FPTT_CITATION_COLAB <- group1(FPTT, "TOM", "PT")

```

FPTT over variables

```{r}

FPTT_FUN <- function(.dataframe, .var1){
  
  var1 <- enquo(.var1)
  
  df <- .dataframe %>%
  group_by(UQ(var1)) %>%
  summarize(FPTT_mean = mean(FPTT),
            FPTT_median = median(FPTT),
            FPTT_IQR = IQR(FPTT),
            FPTT_SD = sd(FPTT))
  
  return(df)
  
}

#Do it for all 11 dataframes. 
FPTT_LATTICE_413_NOLAB <- FPTT_FUN(FPTT_LATTICE_413_NOLAB, population)
FPTT_SMALL_413_NOLAB <- FPTT_FUN(FPTT_SMALL_413_NOLAB, population)
FPTT_LATTICE_484_NOLAB <- FPTT_FUN(FPTT_LATTICE_484_NOLAB, population)
FPTT_SMALL_484_NOLAB <- FPTT_FUN(FPTT_SMALL_484_NOLAB, population)
FPTT_LATTICE_NOLAB <- FPTT_FUN(FPTT_LATTICE_NOLAB, population)
FPTT_SMALL_NOLAB <- FPTT_FUN(FPTT_SMALL_NOLAB, population)
FPTT_LATTICE_COLAB <- FPTT_FUN(FPTT_LATTICE_COLAB, population)
FPTT_SMALL_COLAB <- FPTT_FUN(FPTT_SMALL_COLAB, population)
FPTT_TOM_COLAB <- FPTT_FUN(FPTT_TOM_COLAB, population)
FPTT_PT_COLAB <- FPTT_FUN(FPTT_PT_COLAB, population)
FPTT_CITATION_COLAB <- FPTT_FUN(FPTT_CITATION_COLAB, population)

rm(FPTT, FPTT_FUN, group1, group2, group3)
```

write csv 

```{r}

setwd("~/CRUST-1/MetascienceBA/data/outcome_tables")

writeFUN <- function(df){
  
  df_name <- deparse(substitute(df))
  write_csv(df, paste0(df_name, ".csv"))
  
}

writeFUN(FPTT_LATTICE_413_NOLAB)
writeFUN(FPTT_SMALL_413_NOLAB)
writeFUN(FPTT_LATTICE_484_NOLAB)
writeFUN(FPTT_SMALL_484_NOLAB)
writeFUN(FPTT_LATTICE_NOLAB)
writeFUN(FPTT_SMALL_NOLAB)
writeFUN(FPTT_LATTICE_COLAB)
writeFUN(FPTT_SMALL_COLAB)
writeFUN(FPTT_TOM_COLAB)
writeFUN(FPTT_PT_COLAB)
writeFUN(FPTT_CITATION_COLAB)

```

