---
title: "replication scaled"
author: "Victor Møller"
date: "19 maj 2019"
output: html_document
---

```{r}
#set working directory
setwd("C:/Users/Mikkel/Documents/CRUST-1/DevezerAlteredAgents/data/plotting")

#packages 
library(pacman)
p_load(tidyverse, ggunchained) 
```

loading data. 

```{r}

RR_Devezer <- read_csv("violin_extended_Devezer_original.csv")
RR_MOD <- read_csv("violin_extended_Devezer_fixed.csv")

#as factor
factorize <- function(dataframe){
  df <- dataframe %>%
    mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         true_model = factor(true_model))
  
  return(df)
}

RR_Devezer <- factorize(RR_Devezer)
RR_MOD <- factorize(RR_MOD)

RR_100_both <- RR_MOD %>%
  filter(base_SS == 100)

RR_20_both <- RR_MOD %>%
  filter(base_SS == 20)

RR_20_BIC <- RR_MOD %>%
  filter(base_SS == 20, modelcompare == "BIC")

```

replication overall, main effects. 

```{r}

#RR 
RR_FX <- function(.df, .grouping){
  
  grouping <- enquo(.grouping)
  
  df <- .df %>%
    group_by(UQ(grouping)) %>%
    summarize(RR_median = median(RR),
              RR_mean = mean(RR),
              RR_IQR = IQR(RR),
              RR_SD = sd(RR))
  
  return(df)

}

#cols to group over
colnames(RR)

#cols to group over
RR_Devezer_table <- RR_FX(RR_Devezer, population) #what we write. 
RR_100_both_table <- RR_FX(RR_100_both, population) #what we write. 
RR_20_both_table <- RR_FX(RR_20_both, population) #what we write. 
RR_20_BIC_table <- RR_FX(RR_20_BIC, population) #what we write. 

```

write.csv

```{r}

setwd("~/CRUST-1/DevezerAlteredAgents/data/outcome_tables")
write_csv(RR_Devezer_table, "RR_Devezer.csv")
write_csv(RR_100_both_table, "RR_100_both.csv")
write_csv(RR_20_both_table, "RR_20_both.csv")
write_csv(RR_20_BIC_table, "RR_20_BIC.csv")


```
