---
title: "TAT_TAT50"
author: "Victor Møller"
date: "26 maj 2019"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Set working directory & load libraries. 

```{r}

setwd("D:/data/data_outcome_measures")
library(tidyverse)

```

Loading & Early prep

```{r}

#reading stuff
TAT_ORIG <- read_csv("TAT_TAT50_Devezer_original.csv")
TAT_FIXED <- read_csv("TAT_TAT50_Devezer_fixed.csv")
TAT_ORIG_AVG <- read_csv("TAT_TAT50_AVG_Devezer_original.csv")
TAT_FIXED_AVG <- read_csv("TAT_TAT50_AVG_Devezer_fixed.csv")

#as factor
factorize <- function(dataframe){
  df <- dataframe %>%
    mutate(network = factor(network),
         population = factor(population),
         sigma = factor(sigma),
         true_model = factor(true_model),
         base_SS = factor(base_SS),
         modelcompare = factor(modelcompare))
  
  return(df)
}

TAT_ORIG <- factorize(TAT_ORIG)
TAT_FIXED <- factorize(TAT_FIXED)
TAT_ORIG_AVG <- factorize(TAT_ORIG_AVG)
TAT_FIXED_AVG <- factorize(TAT_FIXED_AVG)

```

Main effects: 

```{r}

#Function approach
TAT_FX <- function(.df, .grouping){

  grouping <- enquo(.grouping)
  
  df <- .df %>%
  group_by(UQ(grouping)) %>%
  summarize(TAT_median = median(TAT),
            TAT_mean = mean(TAT),
            TAT_IQR = IQR(TAT),
            TAT_SD = sd(TAT))
  
  return(df)
  
}

##FOR ORIGINAL DEVEZER ##

colnames(TAT_ORIG) 

#TATS
TAT_POP_ORIG <- TAT_FX(TAT_ORIG, population) #what we write. 
TAT_FX(TAT_ORIG, sigma)
TAT_FX(TAT_ORIG, true_model)
TAT_FX(TAT_ORIG, base_SS)
TAT_FX(TAT_ORIG, modelcompare)

##FOR FIXED DEVEZER ##

colnames(TAT_FIXED) 

#TATS
TAT_POP_FIXED <- TAT_FX(TAT_FIXED, population) #what we write. 
TAT_FX(TAT_FIXED, sigma)
TAT_FX(TAT_FIXED, true_model)
TAT_FX(TAT_FIXED, base_SS)
TAT_FX(TAT_FIXED, modelcompare)

#TAT 50
TAT_50 <- function(.df, .grouping){

  grouping <- enquo(.grouping)
  
  df <- .df %>%
  group_by(UQ(grouping)) %>%
  summarize(TAT50_median = median(TAT50),
            TAT50_mean = mean(TAT50),
            TAT50_IQR = IQR(TAT50),
            TAT50_SD = sd(TAT50))
  
  return(df)
  
}

##FOR ORIGINAL DEVEZER ##

colnames(TAT_ORIG) 

#TATS
TAT50_POP_ORIG <- TAT_50(TAT_ORIG, population) #what we write. 
TAT_50(TAT_ORIG, sigma)
TAT_50(TAT_ORIG, true_model)
TAT_50(TAT_ORIG, base_SS)
TAT_50(TAT_ORIG, modelcompare)

#FOR FIXED

##FOR ORIGINAL DEVEZER ##

colnames(TAT_ORIG) 

#TATS
TAT50_POP_FIXED <- TAT_50(TAT_FIXED, population) #what we write. 
TAT_50(TAT_FIXED, sigma)
TAT_50(TAT_FIXED, true_model)
TAT_50(TAT_FIXED, base_SS)
TAT_50(TAT_FIXED, modelcompare)

```

Interaction effects: 

```{r}

#Function approach
TAT_FX2 <- function(.df, ...){

  group_var <- enquos(...)
  
  df <- .df %>%
  group_by(!!! group_var) %>%
  summarize(TAT_median = round(median(TAT),2),
            TAT_mean = round(mean(TAT),2),
            TAT_IQR = round(IQR(TAT),2),
            TAT50_median = round(median(TAT50),2),
            TAT50_mean = round(mean(TAT50),2),
            TAT50_IQR = round(IQR(TAT50),2))
  
  return(df)
  
}

## FOR ORIGINAL DEVEZER ## 

#overview
colnames(TAT_ORIG)

#interactions
SIGMOD <- TAT_FX2(TAT_ORIG, sigma, true_model) #clear interaction 
SIGPOP <- TAT_FX2(TAT_ORIG, sigma, population) #nothing conclusive
POPMOD <- TAT_FX2(TAT_ORIG, population, true_model) #nothing conclusive

## FOR FIXED ##

#overview
colnames(TAT_ORIG)

#interactions
SIGMOD <- TAT_FX2(TAT_FIXED, sigma, true_model) #clear interaction 
SIGPOP <- TAT_FX2(TAT_FIXED, sigma, population) #nothing conclusive
POPMOD <- TAT_FX2(TAT_FIXED, population, true_model) #nothing conclusive

```

write csv 

```{r}

setwd("~/CRUST-1/MetascienceBA/connectivity/KableTable")
write_csv(TAT_POP, "TAT_POP.csv")
write_csv(TAT50_POP, "TAT50_POP.csv")

```

