---
title: "Untitled"
author: "Victor Møller"
date: "November 30, 2019"
output: html_document
---

```{r setup, include=FALSE}

library(pacman)

setwd("~/CRUST-1")

p_load(igraph, stringr, ggraph, wesanderson, cowplot, caTools, data.table, permute, matrixStats, MCMCpack, tidyverse, rlist, nnet)

```

Paths 

```{r}

baseDir <- "."
scriptDir <- paste0(baseDir, "/FunctionsLoads/Functions")
inputDir <- paste0(baseDir, "/Paper1/data")
outputDirCsv <- paste0(baseDir, "/Paper1/data/raw/csv")
outputDirRds <- paste0(baseDir, "/Paper1/data/raw/rds")


```

Functions

```{r}

source(paste0(scriptDir, "/analysis.R"))
source(paste0(scriptDir, "/calculateDet.R"))
source(paste0(scriptDir, "/calculateDistance.R"))
source(paste0(scriptDir, "/compareModels.R"))
source(paste0(scriptDir, "/constantsPaper1.R"))
source(paste0(scriptDir, "/convertBinary.R"))
source(paste0(scriptDir, "/generateBetas.R"))
source(paste0(scriptDir, "/generateModels.R"))
source(paste0(scriptDir, "/generateXSet.R"))
source(paste0(scriptDir, "/generateY.R"))
source(paste0(scriptDir, "/getBetas.R"))
source(paste0(scriptDir, "/getPredictors.R"))
source(paste0(scriptDir, "/modelSimilarByInteraction.R"))
source(paste0(scriptDir, "/modelSimilarByTerm.R"))
source(paste0(scriptDir, "/modelToStr.R"))
source(paste0(scriptDir, "/searchModel.R"))
source(paste0(scriptDir, "/seedGenerator.R"))
source(paste0(scriptDir, "/abmPaper1Reproducibility.R"))
source(paste0(scriptDir, "/strToModel.R"))

```

Technicalities (comment later)

```{r}

## Output filename
outputFile <- ".csv"
paramFile <- ".rds"

## Verbose mode
verbose <- TRUE

## Number of decimal places
ndec <- 4

```

Input parameters

```{r}

## Number of replications
replications <- 1

## Length of the simulation
timesteps <- 100

## Number of factors
k <- 3

## Correlation
correlation <- 0.2

## Testing stuff here ## 
load(paste0(baseDir, "/FunctionsLoads/Loads/models"))
load(paste0(baseDir, "/FunctionsLoads/Loads/modelsString"))

## Identify the number of predictors of each model
predictors <- getPredictors(models)

## Generate Betas
weights <- generateBetas(models)

## modelselection 
modelSelection <- "hard"

```

Identifiers & variables to be looped over: 
* populations: "Mave", "Tess", "Bo", "All"
* sampleSizes: 100 (but can take all integer values)
* sigmas: 0.2, 0.5, 0.8 (but can take values from 0-1)
* tMods: 2, 7, 13 (but can take values from 1-14, all possible models)
* modelCompares: AIC, BIC

```{r}

#ID variables 
populations <- list("Mave", "Tess", "Bo", "All") 
sampleSizes <- list(100) 

#Variables
sigmas <- list(0.2, 0.5, 0.8)
tMods <- list(2, 7, 13) 
modelCompares <- list(AIC, BIC) 

```

set seed 

```{r}

seeds <- seedGenerator(replications, paste0(inputDir, "/seeds.csv"))

```

Run the function 

```{r}

for (population in populations){
  for (sigma in sigmas){
    for (sampleSize in sampleSizes){
      for (tMod in tMods){
        for (modelCompare in modelCompares){
abmPaper1Reproducibility(replications, timesteps, models, k, tModel,
  nRey, nTess, nBo, nMave, weights, sampleSize, correlation, sigma,
  modelCompare, modelSelection, inputDir, outputDir, outputFile, paramFile,
  verbose, ndec, seeds)
        }
      }
    }
  }
}

```

